#!/bin/bash

##_______________________________________________________________________________
## Clean build of a specific high-level target in the USG code tree

case $1 in 
    "casacore")
	BUILD_TARGET=casacore
	;;
    "cr")
	BUILD_TARGET=cr
	;;
    "dal")
	BUILD_TARGET=dal
	;;
    "rm")
	BUILD_TARGET=rm
	;;
    *)
	echo "[clean_rebuild] No build target selected - please provide one!"
	exit;
	;;
esac

export LOFARSOFT=`pwd`
. ./devel_common/scripts/init.sh

echo "-- Cleaning up directories ..."
rm -rf release build

echo "-- Updating working copy of source code ..."
svn up

echo "-- Starting up build of DAL ..."
cd build
./bootstrap
make ${BUILD_TARGET}

##_______________________________________________________________________________
## Test build with results send to Dashboard server

case $2 in
    "Experimental")
	echo "Experimental build for ${BUILD_TARGET} ..."
	cd $LOFARSOFT/build/${BUILD_TARGET}
	make Experimental
	;;
    "Nightly")
	echo "Nightly build for ${BUILD_TARGET} ..."
	cd $LOFARSOFT/build/${BUILD_TARGET}
	make Nightly
	;;
    "Cluster")
	echo "Cluster install of ${BUILD_TARGET} ..."
	targetdir=/app64/usg
	var_version=`cat $LOFARSOFT/.svn/all-wcprops | grep code | grep trunk | tr "/" "\n" | grep [0-9]`
	echo "SVN version = ${var_version}"
	if test -d $targetdir ; then 
	    echo "-- copying release directory to $targetdir ..."
	    cd $targetdir
	    cp -r $basedir/release release-$var_version
	    echo "-- Cleaning up release directory ..."
	    rm -rf release-$var_version/include
	    echo "-- creating symbolic links ..."
	    rm -f lib bin
	    ln -s release-$var_version/bin .
	    ln -s release-$var_version/lib .
	else
	    echo "Directory $targetdir does not exist - skipping cluster installation!"
	fi
	;;
    *)
	echo "[clean_rebuild] Unknown post-build option."
	echo " "
	echo " [Experimental|Nightly|Cluster] "
	echo " "
	exit;
	;;
esac

