#!/bin/bash

basedir=`pwd`
targetdir=/opt/dal

## ----------------------------------------------------------------------------
## Update codebase and rebuild the DAL

./devel_common/scripts/clean_rebuild dal

## ----------------------------------------------------------------------------
## Get SVN revision number

echo "-- Extracting version number ..."

var_version=`cat $basedir/.svn/all-wcprops | grep code | grep trunk | grep -v CMakeLists | tr "/" "\n" | grep [0-9]`

echo "--> Version number = ${var_version}"

## ----------------------------------------------------------------------------
## Copy the release directory to the installion target

echo "-- copying release directory to $targetdir ..."

cd $targetdir
cp -r $basedir/release release-$var_version

echo "-- Cleaning up release directory ..."

rm -rf release-$var_version/include

echo "-- creating symbolic links ..."

rm -f lib bin
ln -s release-$var_version/bin .
ln -s release-$var_version/lib .

echo "-- post-installation clean-up ..."

rm -rf release-$var_version/doc
rm -rf release-$var_version/man
rm -rf release-$var_version/share
rm -rf release-$var_version/release_area.txt
