#!/bin/sh

##------------------------------------------------------------------------------
## $Id                                                                         $
##------------------------------------------------------------------------------

##------------------------------------------------------------------------------
## When called, make sure, that the script is running from the correct location.

echo "[CR-Tools installer] Checking location for the script to run ..."

if test -d src ; then
    echo " --> Found directory src"
    if test -d external ; then
	echo " --> Found directory external"
    else
	exit 1;
    fi
else
    exit 1;
fi

##------------------------------------------------------------------------------
## Check if we have the build directory; if this is not the case create it

echo "[CR-Tools installer] Checking for build directory ..."

if test -d build ; then
    echo " --> Successfully found build directory."
else
    echo " --> No build directory found - creating it now."
    mkdir -p build
fi

cd build
basedir=`pwd`

##------------------------------------------------------------------------------
## Configure and install the packages required for the CR-Tools

cd build
basedir=`pwd`

$basedir/build.sh cr --force-build

##------------------------------------------------------------------------------
## Required environment variables to set

cd $basedir/..

echo "-----------------------------------------------------------------"
echo "Add the location of the new executables to your PATH variable:"
echo ""
echo " 1) For csh and tcsh"
echo "      set path = ( $path `pwd`/release/bin )"
echo "" 
echo " 2) For sh and bash"
echo "      export PATH=$PATH:`pwd`/release/bin"
echo "-----------------------------------------------------------------"
