#!/bin/sh

##------------------------------------------------------------------------------
## $Id                                                                         $
##------------------------------------------------------------------------------

##------------------------------------------------------------------------------
## When called, make sure, that the script is running from the correct location.

echo "[DAL installer] Checking location for the script to run ..."

if test -d src ; then
    echo " --> Found directory src"
    if test -d external ; then
	echo " --> Found directory external"
    else
	exit 1;
    fi
else
    exit 1;
fi

##------------------------------------------------------------------------------
## Check if we have the build directory; if this is not the case create it

echo "[DAL installer] Checking for build directory ..."

if test -d build ; then
    echo " --> Successfully found build directory."
else
    echo " --> No build directory found - creating it now."
    mkdir -p build
fi

##------------------------------------------------------------------------------
## Configure and install the DAL (including required 3rd-party packages)

cd build
basedir=`pwd`

$basedir/build.sh dal --force-build

##------------------------------------------------------------------------------
## Feedback on post-install user activities

