.TH "/home/vilchez/Bureau/dynspec/src/ICD3-ICD6-Complete/Reader_Root.cpp" 3 "Thu Jan 10 2013" "LOFAR-ICD3 Convertor without any  selection and rebinning" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/vilchez/Bureau/dynspec/src/ICD3-ICD6-Complete/Reader_Root.cpp \- 
.PP
File C++ (associated to \fBReader_Root\&.h\fP) for read ICD3 files and put in variables metadatas for the ICD6's Root Group\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include 'Reader_Root\&.h'\fP
.br
\fC#include 'Stock_Write_Root_Metadata\&.h'\fP
.br
\fC#include <dal/lofar/BF_File\&.h>\fP
.br

.SH "Detailed Description"
.PP 
File C++ (associated to \fBReader_Root\&.h\fP) for read ICD3 files and put in variables metadatas for the ICD6's Root Group\&. 


.br
 Overview: 
.br
 This function readRoot is described (programmed) here\&. It needs as parameter a Stock_Write_Root_Metadata_Part object\&. The readRoot function will read root metadatas and stock them in the Stock_Write_Root_Metadata_Part object as private attributes thanks to stockRootMetadata function\&. These attributes will be written in the next step by writeRootMetadata function which is in the class Stock_Write_Root_Metadata_Part\&.h and called at the end of this \fBReader_Root\&.cpp\fP 
.SH "Author"
.PP 
Generated automatically by Doxygen for LOFAR-ICD3 Convertor without any selection and rebinning from the source code\&.
