.TH "/home/vilchez/Bureau/dynspec/src/ICD3-ICD6-Complete/Reader_Dynspec.h" 3 "Thu Jan 10 2013" "LOFAR-ICD3 Convertor without any  selection and rebinning" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/vilchez/Bureau/dynspec/src/ICD3-ICD6-Complete/Reader_Dynspec.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <dal/lofar/BF_File\&.h>\fP
.br
\fC#include 'Stock_Write_Dynspec_Metadata\&.h'\fP
.br
\fC#include 'Stock_Write_Dynspec_Data\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBReader_Dynspec\fP"
.br
.RI "\fIClass object for read ICD3 files and put in variables metadatas for the ICD6's Dynspec Group\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LOFAR-ICD3 Convertor without any selection and rebinning from the source code\&.
