.TH "/home/vilchez/Bureau/dynspec/src/ICD3-ICD6-Complete/Stock_Write_Dynspec_Metadata.h" 3 "Thu Jan 10 2013" "LOFAR-ICD3 Convertor without any  selection and rebinning" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/vilchez/Bureau/dynspec/src/ICD3-ICD6-Complete/Stock_Write_Dynspec_Metadata.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <dal/lofar/BF_File\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBStock_Write_Dynspec_Metadata\fP"
.br
.RI "\fIClass object for stock and write metadatas for the ICD6's Dynspec Groups (loop on Beams \&.\&.\&.) \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LOFAR-ICD3 Convertor without any selection and rebinning from the source code\&.
