.TH "/home/vilchez/Bureau/dynspec/src/ICD3-ICD6-Complete/Stock_Write_Root_Metadata.cpp" 3 "Thu Jan 10 2013" "LOFAR-ICD3 Convertor without any  selection and rebinning" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/vilchez/Bureau/dynspec/src/ICD3-ICD6-Complete/Stock_Write_Root_Metadata.cpp \- 
.PP
File C++ (associated to \fBStock_Write_Root_Metadata\&.h\fP) for stock and write metadatas for the ICD6's Root Group\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br
\fC#include 'Stock_Write_Root_Metadata\&.h'\fP
.br
\fC#include <dal/lofar/BF_File\&.h>\fP
.br

.SH "Detailed Description"
.PP 
File C++ (associated to \fBStock_Write_Root_Metadata\&.h\fP) for stock and write metadatas for the ICD6's Root Group\&. 


.br
 Overview: 
.br
 Functions stockRootMetadata and writeRootMetadata are described (programmed) here\&. The first one (stockRootMetadata) will take as parameter all Root Group's metadata and stock them in the private attributes of the class object\&. The second function (writeRootMetadata) will write them in the hdf5 output file\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for LOFAR-ICD3 Convertor without any selection and rebinning from the source code\&.
