# $Id: makefile,v 1.6 2006/10/19 08:31:02 bahren Exp $

OPT:=2

XLIBLIST := WCSLIB LAPACK F77 GLISH CFITSIO

# Use the generic AIPS++ test makefile.
#--------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.tst
