/********************************************************************
* RootDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error RootDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableRootDict();
extern void G__cpp_setup_inheritanceRootDict();
extern void G__cpp_setup_typetableRootDict();
extern void G__cpp_setup_memvarRootDict();
extern void G__cpp_setup_globalRootDict();
extern void G__cpp_setup_memfuncRootDict();
extern void G__cpp_setup_funcRootDict();
extern void G__set_cpp_environmentRootDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "PulseProperties.h"

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__RootDictLN_TClass;
extern G__linked_taginfo G__RootDictLN_TBuffer;
extern G__linked_taginfo G__RootDictLN_TMemberInspector;
extern G__linked_taginfo G__RootDictLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__RootDictLN_string;
extern G__linked_taginfo G__RootDictLN_PulseProperties;

/* STUB derived class for protected member access */
