//
// File generated by rootcint at Sat Jul 24 22:03:50 2010

// Do NOT change. Changes will be lost next time file is generated
//

#include "RConfig.h"
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "RootDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void PulseProperties_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static void *new_PulseProperties(void *p = 0);
   static void *newArray_PulseProperties(Long_t size, void *p);
   static void delete_PulseProperties(void *p);
   static void deleteArray_PulseProperties(void *p);
   static void destruct_PulseProperties(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::PulseProperties*)
   {
      ::PulseProperties *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::PulseProperties >(0);
      static ::ROOT::TGenericClassInfo 
         instance("PulseProperties", ::PulseProperties::Class_Version(), "PulseProperties.h", 68,
                  typeid(::PulseProperties), DefineBehavior(ptr, ptr),
                  &::PulseProperties::Dictionary, isa_proxy, 0,
                  sizeof(::PulseProperties) );
      instance.SetNew(&new_PulseProperties);
      instance.SetNewArray(&newArray_PulseProperties);
      instance.SetDelete(&delete_PulseProperties);
      instance.SetDeleteArray(&deleteArray_PulseProperties);
      instance.SetDestructor(&destruct_PulseProperties);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::PulseProperties*)
   {
      return GenerateInitInstanceLocal((::PulseProperties*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::PulseProperties*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *PulseProperties::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *PulseProperties::Class_Name()
{
   return "PulseProperties";
}

//______________________________________________________________________________
const char *PulseProperties::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::PulseProperties*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int PulseProperties::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::PulseProperties*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void PulseProperties::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::PulseProperties*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *PulseProperties::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::PulseProperties*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void PulseProperties::Streamer(TBuffer &R__b)
{
   // Stream an object of class PulseProperties.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      R__b >> height;
      R__b >> heightError;
      R__b >> time;
      R__b >> timeError;
      R__b >> antennaID;
      R__b >> antenna;
      R__b >> maximum;
      R__b >> envelopeMaximum;
      R__b >> minimum;
      R__b >> maximumTime;
      R__b >> envelopeTime;
      R__b >> minimumTime;
      R__b >> halfheightTime;
      R__b >> geomDelay;
      R__b >> fwhm;
      R__b >> distX;
      R__b >> distXerr;
      R__b >> distY;
      R__b >> distYerr;
      R__b >> distZ;
      R__b >> distZerr;
      R__b >> dist;
      R__b >> disterr;
      R__b >> angleToCore;
      R__b >> angleToCoreerr;
      R__b >> noise;
      R__b >> lateralExpHeight;
      R__b >> lateralExpDeviation;
      R__b >> lateralPowHeight;
      R__b >> lateralPowDeviation;
      R__b >> lateralCut;
      { TString R__str; R__str.Streamer(R__b); polarization = R__str.Data(); }
      R__b >> minMaxSign;
      R__b >> envSign;
      R__b.CheckByteCount(R__s, R__c, PulseProperties::IsA());
   } else {
      R__c = R__b.WriteVersion(PulseProperties::IsA(), kTRUE);
      R__b << height;
      R__b << heightError;
      R__b << time;
      R__b << timeError;
      R__b << antennaID;
      R__b << antenna;
      R__b << maximum;
      R__b << envelopeMaximum;
      R__b << minimum;
      R__b << maximumTime;
      R__b << envelopeTime;
      R__b << minimumTime;
      R__b << halfheightTime;
      R__b << geomDelay;
      R__b << fwhm;
      R__b << distX;
      R__b << distXerr;
      R__b << distY;
      R__b << distYerr;
      R__b << distZ;
      R__b << distZerr;
      R__b << dist;
      R__b << disterr;
      R__b << angleToCore;
      R__b << angleToCoreerr;
      R__b << noise;
      R__b << lateralExpHeight;
      R__b << lateralExpDeviation;
      R__b << lateralPowHeight;
      R__b << lateralPowDeviation;
      R__b << lateralCut;
      { TString R__str = polarization.c_str(); R__str.Streamer(R__b);}
      R__b << minMaxSign;
      R__b << envSign;
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void PulseProperties::ShowMembers(TMemberInspector &R__insp, char *R__parent)
{
      // Inspect the data members of an object of class PulseProperties.
      TClass *R__cl = ::PulseProperties::IsA();
      Int_t R__ncp = strlen(R__parent);
      if (R__ncp || R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__parent, "height", &height);
      R__insp.Inspect(R__cl, R__parent, "heightError", &heightError);
      R__insp.Inspect(R__cl, R__parent, "time", &time);
      R__insp.Inspect(R__cl, R__parent, "timeError", &timeError);
      R__insp.Inspect(R__cl, R__parent, "antennaID", &antennaID);
      R__insp.Inspect(R__cl, R__parent, "antenna", &antenna);
      R__insp.Inspect(R__cl, R__parent, "maximum", &maximum);
      R__insp.Inspect(R__cl, R__parent, "envelopeMaximum", &envelopeMaximum);
      R__insp.Inspect(R__cl, R__parent, "minimum", &minimum);
      R__insp.Inspect(R__cl, R__parent, "maximumTime", &maximumTime);
      R__insp.Inspect(R__cl, R__parent, "envelopeTime", &envelopeTime);
      R__insp.Inspect(R__cl, R__parent, "minimumTime", &minimumTime);
      R__insp.Inspect(R__cl, R__parent, "halfheightTime", &halfheightTime);
      R__insp.Inspect(R__cl, R__parent, "geomDelay", &geomDelay);
      R__insp.Inspect(R__cl, R__parent, "fwhm", &fwhm);
      R__insp.Inspect(R__cl, R__parent, "distX", &distX);
      R__insp.Inspect(R__cl, R__parent, "distXerr", &distXerr);
      R__insp.Inspect(R__cl, R__parent, "distY", &distY);
      R__insp.Inspect(R__cl, R__parent, "distYerr", &distYerr);
      R__insp.Inspect(R__cl, R__parent, "distZ", &distZ);
      R__insp.Inspect(R__cl, R__parent, "distZerr", &distZerr);
      R__insp.Inspect(R__cl, R__parent, "dist", &dist);
      R__insp.Inspect(R__cl, R__parent, "disterr", &disterr);
      R__insp.Inspect(R__cl, R__parent, "angleToCore", &angleToCore);
      R__insp.Inspect(R__cl, R__parent, "angleToCoreerr", &angleToCoreerr);
      R__insp.Inspect(R__cl, R__parent, "noise", &noise);
      R__insp.Inspect(R__cl, R__parent, "lateralExpHeight", &lateralExpHeight);
      R__insp.Inspect(R__cl, R__parent, "lateralExpDeviation", &lateralExpDeviation);
      R__insp.Inspect(R__cl, R__parent, "lateralPowHeight", &lateralPowHeight);
      R__insp.Inspect(R__cl, R__parent, "lateralPowDeviation", &lateralPowDeviation);
      R__insp.Inspect(R__cl, R__parent, "lateralCut", &lateralCut);
      R__insp.Inspect(R__cl, R__parent, "polarization", (void*)&polarization);
      ::ROOT::GenericShowMembers("string", (void*)&polarization, R__insp, strcat(R__parent,"polarization."),false);
      R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "minMaxSign", &minMaxSign);
      R__insp.Inspect(R__cl, R__parent, "envSign", &envSign);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_PulseProperties(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::PulseProperties : new ::PulseProperties;
   }
   static void *newArray_PulseProperties(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::PulseProperties[nElements] : new ::PulseProperties[nElements];
   }
   // Wrapper around operator delete
   static void delete_PulseProperties(void *p) {
      delete ((::PulseProperties*)p);
   }
   static void deleteArray_PulseProperties(void *p) {
      delete [] ((::PulseProperties*)p);
   }
   static void destruct_PulseProperties(void *p) {
      typedef ::PulseProperties current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::PulseProperties

/********************************************************
* RootDict.C
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

extern "C" void G__cpp_reset_tagtableRootDict();

extern "C" void G__set_cpp_environmentRootDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("PulseProperties.h");
  G__cpp_reset_tagtableRootDict();
}
#include <new>
extern "C" int G__cpp_dllrevRootDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* PulseProperties */
static int G__RootDict_92_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   PulseProperties* p = NULL;
   long gvp = G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == G__PVOID) || (gvp == 0)) {
       p = new PulseProperties[n];
     } else {
       p = new((void*) gvp) PulseProperties[n];
     }
   } else {
     if ((gvp == G__PVOID) || (gvp == 0)) {
       p = new PulseProperties;
     } else {
       p = new((void*) gvp) PulseProperties;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   result7->type = 'u';
   result7->tagnum = G__get_linked_tagnum(&G__RootDictLN_PulseProperties);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RootDict_92_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const string* pobj;
         const string xobj = ((const PulseProperties*) G__getstructoffset())->className();
         pobj = new string(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RootDict_92_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PulseProperties*) G__getstructoffset())->summary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RootDict_92_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PulseProperties*) G__getstructoffset())->summary(*(ostream*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RootDict_92_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) PulseProperties::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RootDict_92_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) PulseProperties::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RootDict_92_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) PulseProperties::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RootDict_92_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      PulseProperties::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RootDict_92_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((const PulseProperties*) G__getstructoffset())->IsA());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RootDict_92_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PulseProperties*) G__getstructoffset())->ShowMembers(*(TMemberInspector*) libp->para[0].ref, (char*) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RootDict_92_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PulseProperties*) G__getstructoffset())->Streamer(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RootDict_92_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PulseProperties*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RootDict_92_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) PulseProperties::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RootDict_92_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) PulseProperties::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RootDict_92_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) PulseProperties::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RootDict_92_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) PulseProperties::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__RootDict_92_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   PulseProperties* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new PulseProperties(*(PulseProperties*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   result7->type = 'u';
   result7->tagnum = G__get_linked_tagnum(&G__RootDictLN_PulseProperties);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef PulseProperties G__TPulseProperties;
static int G__RootDict_92_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   long gvp = G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == G__PVOID) {
       delete[] (PulseProperties*) soff;
     } else {
       G__setgvp(G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((PulseProperties*) (soff+(sizeof(PulseProperties)*i)))->~G__TPulseProperties();
       }
       G__setgvp(gvp);
     }
   } else {
     if (gvp == G__PVOID) {
       delete (PulseProperties*) soff;
     } else {
       G__setgvp(G__PVOID);
       ((PulseProperties*) (soff))->~G__TPulseProperties();
       G__setgvp(gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__RootDict_92_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   PulseProperties* dest = (PulseProperties*) G__getstructoffset();
   *dest = *(PulseProperties*) libp->para[0].ref;
   const PulseProperties& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* PulseProperties */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncRootDict {
 public:
  G__Sizep2memfuncRootDict(): p(&G__Sizep2memfuncRootDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncRootDict::*p)();
};

size_t G__get_sizep2memfuncRootDict()
{
  G__Sizep2memfuncRootDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceRootDict() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableRootDict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* PulseProperties */
static void G__setup_memvarPulseProperties(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__RootDictLN_PulseProperties));
   { PulseProperties *p; p=(PulseProperties*)0x1000; if (p) { }
   G__memvar_setup((void*)0,108,0,0,-1,-1,-1,4,"G__virtualinfo=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->height)-(long)(p)),100,0,0,-1,-1,-1,1,"height=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->heightError)-(long)(p)),100,0,0,-1,-1,-1,1,"heightError=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->time)-(long)(p)),100,0,0,-1,-1,-1,1,"time=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->timeError)-(long)(p)),100,0,0,-1,-1,-1,1,"timeError=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->antennaID)-(long)(p)),105,0,0,-1,-1,-1,1,"antennaID=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->antenna)-(long)(p)),105,0,0,-1,-1,-1,1,"antenna=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->maximum)-(long)(p)),100,0,0,-1,-1,-1,1,"maximum=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->envelopeMaximum)-(long)(p)),100,0,0,-1,-1,-1,1,"envelopeMaximum=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->minimum)-(long)(p)),100,0,0,-1,-1,-1,1,"minimum=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->maximumTime)-(long)(p)),100,0,0,-1,-1,-1,1,"maximumTime=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->envelopeTime)-(long)(p)),100,0,0,-1,-1,-1,1,"envelopeTime=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->minimumTime)-(long)(p)),100,0,0,-1,-1,-1,1,"minimumTime=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->halfheightTime)-(long)(p)),100,0,0,-1,-1,-1,1,"halfheightTime=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->geomDelay)-(long)(p)),100,0,0,-1,-1,-1,1,"geomDelay=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fwhm)-(long)(p)),100,0,0,-1,-1,-1,1,"fwhm=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->distX)-(long)(p)),100,0,0,-1,-1,-1,1,"distX=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->distXerr)-(long)(p)),100,0,0,-1,-1,-1,1,"distXerr=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->distY)-(long)(p)),100,0,0,-1,-1,-1,1,"distY=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->distYerr)-(long)(p)),100,0,0,-1,-1,-1,1,"distYerr=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->distZ)-(long)(p)),100,0,0,-1,-1,-1,1,"distZ=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->distZerr)-(long)(p)),100,0,0,-1,-1,-1,1,"distZerr=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->dist)-(long)(p)),100,0,0,-1,-1,-1,1,"dist=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->disterr)-(long)(p)),100,0,0,-1,-1,-1,1,"disterr=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->angleToCore)-(long)(p)),100,0,0,-1,-1,-1,1,"angleToCore=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->angleToCoreerr)-(long)(p)),100,0,0,-1,-1,-1,1,"angleToCoreerr=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->noise)-(long)(p)),100,0,0,-1,-1,-1,1,"noise=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->lateralExpHeight)-(long)(p)),100,0,0,-1,-1,-1,1,"lateralExpHeight=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->lateralExpDeviation)-(long)(p)),100,0,0,-1,-1,-1,1,"lateralExpDeviation=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->lateralPowHeight)-(long)(p)),100,0,0,-1,-1,-1,1,"lateralPowHeight=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->lateralPowDeviation)-(long)(p)),100,0,0,-1,-1,-1,1,"lateralPowDeviation=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->lateralCut)-(long)(p)),103,0,0,-1,-1,-1,1,"lateralCut=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->polarization)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__RootDictLN_string),-1,-1,1,"polarization=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->minMaxSign)-(long)(p)),105,0,0,-1,-1,-1,1,"minMaxSign=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->envSign)-(long)(p)),105,0,0,-1,-1,-1,1,"envSign=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__RootDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarRootDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncPulseProperties(void) {
   /* PulseProperties */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__RootDictLN_PulseProperties));
   G__memfunc_setup("PulseProperties",1590,G__RootDict_92_0_1, 105, G__get_linked_tagnum(&G__RootDictLN_PulseProperties), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("className",919,G__RootDict_92_0_2, 117, G__get_linked_tagnum(&G__RootDictLN_string), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("summary",782,G__RootDict_92_0_3, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("summary",782,G__RootDict_92_0_4, 121, -1, -1, 0, 1, 1, 1, 0, "u 'basic_ostream<char,char_traits<char> >' 'ostream' 1 - os", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__RootDict_92_0_5, 85, G__get_linked_tagnum(&G__RootDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) (TClass* (*)())(&PulseProperties::Class), 0);
   G__memfunc_setup("Class_Name",982,G__RootDict_92_0_6, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) (const char* (*)())(&PulseProperties::Class_Name), 0);
   G__memfunc_setup("Class_Version",1339,G__RootDict_92_0_7, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) (Version_t (*)())(&PulseProperties::Class_Version), 0);
   G__memfunc_setup("Dictionary",1046,G__RootDict_92_0_8, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) (void (*)())(&PulseProperties::Dictionary), 0);
   G__memfunc_setup("IsA",253,G__RootDict_92_0_9, 85, G__get_linked_tagnum(&G__RootDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,G__RootDict_92_0_10, 121, -1, -1, 0, 2, 1, 1, 0, 
"u 'TMemberInspector' - 1 - insp C - - 0 - parent", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,G__RootDict_92_0_11, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__RootDict_92_0_12, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__RootDict_92_0_13, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) (const char* (*)())(&PulseProperties::DeclFileName), 0);
   G__memfunc_setup("ImplFileLine",1178,G__RootDict_92_0_14, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) (int (*)())(&PulseProperties::ImplFileLine), 0);
   G__memfunc_setup("ImplFileName",1171,G__RootDict_92_0_15, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) (const char* (*)())(&PulseProperties::ImplFileName), 0);
   G__memfunc_setup("DeclFileLine",1152,G__RootDict_92_0_16, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) (int (*)())(&PulseProperties::DeclFileLine), 0);
   // automatic copy constructor
   G__memfunc_setup("PulseProperties", 1590, G__RootDict_92_0_17, (int) ('i'), G__get_linked_tagnum(&G__RootDictLN_PulseProperties), -1, 0, 1, 1, 1, 0, "u 'PulseProperties' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~PulseProperties", 1716, G__RootDict_92_0_18, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__RootDict_92_0_19, (int) ('u'), G__get_linked_tagnum(&G__RootDictLN_PulseProperties), -1, 1, 1, 1, 1, 0, "u 'PulseProperties' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncRootDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalRootDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcRootDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__RootDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__RootDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__RootDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__RootDictLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR = { "basic_ostream<char,char_traits<char> >" , 99 , -1 };
G__linked_taginfo G__RootDictLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__RootDictLN_PulseProperties = { "PulseProperties" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableRootDict() {
  G__RootDictLN_TClass.tagnum = -1 ;
  G__RootDictLN_TBuffer.tagnum = -1 ;
  G__RootDictLN_TMemberInspector.tagnum = -1 ;
  G__RootDictLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR.tagnum = -1 ;
  G__RootDictLN_string.tagnum = -1 ;
  G__RootDictLN_PulseProperties.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableRootDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__RootDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__RootDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__RootDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__RootDictLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR);
   G__get_linked_tagnum_fwd(&G__RootDictLN_string);
   G__tagtable_setup(G__get_linked_tagnum(&G__RootDictLN_PulseProperties),sizeof(PulseProperties),-1,1280,(char*)NULL,G__setup_memvarPulseProperties,G__setup_memfuncPulseProperties);
}
extern "C" void G__cpp_setupRootDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupRootDict()");
  G__set_cpp_environmentRootDict();
  G__cpp_setup_tagtableRootDict();

  G__cpp_setup_inheritanceRootDict();

  G__cpp_setup_typetableRootDict();

  G__cpp_setup_memvarRootDict();

  G__cpp_setup_memfuncRootDict();
  G__cpp_setup_globalRootDict();
  G__cpp_setup_funcRootDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncRootDict();
  return;
}
class G__cpp_setup_initRootDict {
  public:
    G__cpp_setup_initRootDict() { G__add_setup_func("RootDict",(G__incsetup)(&G__cpp_setupRootDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initRootDict() { G__remove_setup_func("RootDict"); }
};
G__cpp_setup_initRootDict G__cpp_setup_initializerRootDict;

