#! /bin/bash
# first run makeparadefine and then edit if necessary 
# and then run makegsmparadefine and edit if necc.

ransubbdsm ()
{        

if [ -f "$1.gaul" ] && [ -f "$1.gaul.bin" ] && [ -f "$1.gaul.star" ] && [ -f "$1.header" ] && [ -f "$1.srl" ] && [ -f "$1.srl.bin" ] ;  then
  return 1
else
  return 0
fi
}

export EDITR=vi

echo ' '
echo ' Setting up gsmparadefine file ... '
printf ' %s\n Use the (f)ile gsm_fits_list or create (n)ew one ? '
read ch1

if [ $ch1 != "n" ] && [ $ch1 != "f" ] ; then
 export ch1='f'
fi

# set up env variables from paradefine
export file='paradefine'; exec 3<&0; exec 0<$file; 
while read line
do
 f1=$(echo $line | awk '{ print $1 }')
 f3=$(echo $line | awk '{ print $3 }' | sed "s/'//"g)
 export $(echo $f1)=$(echo $f3)
done
exec 0<&3

# list fits files for user to edit
export ppwd=$PWD
cd $scratch; 
if [ $ch1 = "n" ] ; then
 echo ' Edit the following file to include what you need'
 ls *.gaul | grep -v "\.ini\."  > $scratch/a
 sed -e 's/\.gaul$//' -e 's/\(.*\)\./\1 /g' $scratch/a | awk '{print $1}' > $scratch/gsm_list1
 $EDITR $scratch/gsm_list1
else
 echo ' Using old gsm_fits_list'
fi
cd $ppwd

printf ' %s\n Proceed ? '
read

# get the solnnames for the fits files selected 
export file=$scratch/gsm_list1; exec 3<&0; exec 0<$file; rm -fr $scratch/gsm_dum1
export ppwd=$PWD; cd $srldir
while read line
do
 ls $line.*.gaul | grep -v "\.ini" | sed -e 's/\.gaul$//'  >> $scratch/gsm_dum1
done
exec 0<&3
cd $ppwd

# check if all files present
export file=$scratch/gsm_dum1
rm -fr $scratch/gsm_fits_list
exec 3<&0; exec 0<$file; export ppwd=$PWD; cd $srldir
while read line
do
 ransubbdsm $line
 return_val=$?
 if [ "$return_val" -eq 1 ]
 then
  name=`echo $line | sed -e 's/\(.*\)\./\1 /' | sed -s 's/$/ 1/'` 
 else
  name=`echo $line | sed -e 's/\(.*\)\./\1 /' | awk '{print $1}' | sed 's/$/ NONE 1/'`
 fi  
 name1=`echo $name | awk '{print $1}'`
# if [ -f $fitsdir$name1'.fits' -o  -f $fitsdir$name1'.FITS' ] ;  then
  echo $name  >> $scratch/gsm_fits_list
# fi
done
exec 0<&3
cd $ppwd

echo ' Edit the following file to include what you need'
echo ' First field is the name of the fits file (without extension) '
echo ' Second field is the id of the solution. NONE => change it to something else.'
echo ' Third field is 1 => use for fit, and is 0 = > dont fit but just plot.'
echo
$EDITR $scratch/gsm_fits_list

printf ' %s\n Proceed ? '
read

# Now to make file listing of all freqs u want gsm at
printf ' %s\n Use the (f)ile gsm_freqs or create (n)ew one ? '
read ch1
if [ $ch1 != "n" ] && [ $ch1 != "f" ] ; then
 export ch1='f'
fi

# list freq file for user to edit
export ppwd=$PWD
cd $scratch; 
if [ $ch1 = "n" ] ; then
 echo '30.00' > $scratch/gsm_freqs 
 echo '75.00' >> $scratch/gsm_freqs 
 echo ' Edit the following file to include the frequencies (in MHz)'
 echo ' where a GSM is needed.'
 $EDITR $scratch/gsm_freqs
else
 echo ' Using old gsm_freqs'
fi
cd $ppwd

printf ' %s\n Proceed ? '
read
echo '' 

if [ $(wc -l $scratch/gsm_freqs | awk '{print $1}') -gt 0 ] ; then
 echo 'END' >> $scratch/gsm_freqs
 echo 'Lower_spin00 = -2.00' >> $scratch/gsm_freqs
 echo 'Upper_spin00 =  0.00'  >> $scratch/gsm_freqs
 echo 'Lower_sp00-s10_med = -0.3' >> $scratch/gsm_freqs
 echo 'Upper_sp00-s10_med = 0.3' >> $scratch/gsm_freqs
 echo 'Lower_sp11_med = -0.5' >> $scratch/gsm_freqs
 echo 'Upper_sp11_med = 0.5' >> $scratch/gsm_freqs
 echo 'Upper_sp00-s10-s11_med = -0.3' >> $scratch/gsm_freqs
 echo 'Lower_sp00-s10-s11_med =  0.3' >> $scratch/gsm_freqs
 echo ' Edit the following file to change limits if needed.'
 echo ' Upper and lower limits=0 => condition not imposed'
 $EDITR $scratch/gsm_freqs
 printf ' %s\n Proceed ? '
 read
 echo '' 
fi


exit 0


