.TH "/home/vilchez/Bureau/dynspec/src/ICD3-ICD6-Rebin/Reader_Dynspec_Part.h" 3 "Wed Dec 19 2012" "LOFAR-ICD3 Convertor with selection and/or rebinning" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/vilchez/Bureau/dynspec/src/ICD3-ICD6-Rebin/Reader_Dynspec_Part.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <dal/lofar/BF_File\&.h>\fP
.br
\fC#include 'Stock_Write_Dynspec_Metadata_Part\&.h'\fP
.br
\fC#include 'Stock_Write_Dynspec_Data_Part\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBReader_Dynspec_Part\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LOFAR-ICD3 Convertor with selection and/or rebinning from the source code\&.
