.TH "/home/vilchez/Bureau/dynspec/src/ICD3-ICD6-Rebin/Reader_Root_Part.h" 3 "Fri Jan 4 2013" "LOFAR-ICD3 Convertor with selection and/or rebinning" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/vilchez/Bureau/dynspec/src/ICD3-ICD6-Rebin/Reader_Root_Part.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <dal/lofar/BF_File\&.h>\fP
.br
\fC#include 'Stock_Write_Root_Metadata_Part\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBReader_Root_Part\fP"
.br
.RI "\fIClass object for read ICD3 files and put in variables metadatas for the ICD6's Root Group\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for LOFAR-ICD3 Convertor with selection and/or rebinning from the source code\&.
