.TH "Reader_Root_Part" 3 "Thu Jan 10 2013" "LOFAR-ICD3 Convertor with selection and/or rebinning" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Reader_Root_Part \- 
.PP
Class object for read ICD3 files and put in variables metadatas for the ICD6's Root Group\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Reader_Root_Part\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBreadRoot\fP (std::string pathFile, std::string obsName, \fBStock_Write_Root_Metadata_Part\fP *rootMetadata, int obsNofSource, int obsNofBeam, int obsNofFrequencyBand, int obsNofTiledDynspec, std::string SAPname, int SAPindex, float timeMinSelect, float timeMaxSelect, float timeRebin, float frequencyMin, float frequencyMax, float frequencyRebin)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class object for read ICD3 files and put in variables metadatas for the ICD6's Root Group\&. 


.br
 Usage: 
.br
 This class need as parameter a \fBStock_Write_Root_Metadata_Part\fP object\&. The readRoot function will read root metadatas and stock them in the \fBStock_Write_Root_Metadata_Part\fP object as private attributes\&. These attributes will be written in the next step by stockRootMetadata function which is in the class \fBStock_Write_Root_Metadata_Part\&.h\fP 
.SH "Member Function Documentation"
.PP 
.SS "void \fBReader_Root_Part::readRoot\fP (std::stringpathFile, std::stringobsName, \fBStock_Write_Root_Metadata_Part\fP *rootMetadata, intobsNofSource, intobsNofBeam, intobsNofFrequencyBand, intobsNofTiledDynspec, std::stringSAPname, intSAPindex, floattimeMinSelect, floattimeMaxSelect, floattimeRebin, floatfrequencyMin, floatfrequencyMax, floatfrequencyRebin)"
.br
 Usage: 
.br
 void Reader_Root_Part::readRoot(string pathFile,string obsName,Stock_Write_Root_Metadata_Part *rootMetadata,int obsNofSource,int obsNofBeam,int obsNofFrequencyBand,int obsNofTiledDynspec, string SAPname, int SAPindex,float timeMinSelect,float timeMaxSelect,float timeRebin,float frequencyMin,float frequencyMax,float frequencyRebin)
.PP
\fBParameters:\fP
.RS 4
\fIpathFileICD3\fP file to read 
.br
\fIobsName\fP observation ID 
.br
\fI*rootMetadata\fP \fBStock_Write_Root_Metadata_Part\fP class object 
.br
\fIobsNofSource\fP number of sources 
.br
\fIobsNofBeam\fP number of beam 
.br
\fIobsNofFrequencyBandnumber\fP of frequency band 
.br
\fIobsNofTiledDynspecnumber\fP of tiled dynspec 
.br
\fISAPname\fP name of SubArrayPointing 
.br
\fISAPindex\fP index of SubArrayPointing 
.br
\fItimeMinSelect\fP minimum time selection 
.br
\fItimeMaxSelect\fP maximum time selection 
.br
\fItimeRebin\fP time rebinning 
.br
\fIfrequencyMin\fP minimum frequency selection 
.br
\fIfrequencyMax\fP maximum frequency selection 
.br
\fIfrequencyRebin\fP frequency rebinning
.RE
.PP
\fBReturns:\fP
.RS 4
nothing 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for LOFAR-ICD3 Convertor with selection and/or rebinning from the source code\&.
