.TH "Stock_Write_Dynspec_Data_Part" 3 "Thu Jan 10 2013" "LOFAR-ICD3 Convertor with selection and/or rebinning" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Stock_Write_Dynspec_Data_Part \- 
.PP
Class object for stocking data parameters, processing the (select or rebin) and write data Matrix in the ICD6's Dynspec Groups\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Stock_Write_Dynspec_Data_Part\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBstockDynspecData\fP (int Ntime, int Nspectral, int NtimeReal, int NspectralReal)"
.br
.ti -1c
.RI "void \fBwriteDynspecData\fP (Group &dynspec_grp, std::string pathDir, std::string obsName, std::string pathFile, std::string outputFile, File &root_grp, int i, int j, int k, int l, int q, int obsNofStockes, std::vector< std::string > stokesComponent, float memoryRAM, int SAPindex, float timeMinSelect, float timeMaxSelect, float timeRebin, float frequencyMin, float frequencyMax, float frequencyRebin)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class object for stocking data parameters, processing the (select or rebin) and write data Matrix in the ICD6's Dynspec Groups\&. 


.br
 Usage: 
.br
 This class need as parameter all metadata of the dynamic spectrum Goup for process the data\&. Data have 3 dimensions (at the opposite to ICD3 data which have 2)\&. The additionnal dimension is Stokes\&. The function stockDynspecData stocks paramerter (for rebinning the data) in private attributes, and the function writeDynspecData process the data themselves\&. 
.SH "Member Function Documentation"
.PP 
.SS "void \fBStock_Write_Dynspec_Data_Part::stockDynspecData\fP (intNtime, intNspectral, intNtimeReal, intNspectralReal)"
.br
 Usage: 
.br
 void \fBStock_Write_Dynspec_Data_Part::stockDynspecData(int Ntime,int Nspectral,  int NtimeReal, int NspectralReal)\fP 
.PP
\fBParameters:\fP
.RS 4
\fINtime\fP new time binning 
.br
\fINspectral\fP new spectral (frequency) binning (number of channels per subbands) 
.br
\fINtimeReal\fP current time binning before rebinning 
.br
\fINspectralReal\fP current spectral (frequency) binning (number of channels per subbands) before rebinning 
.RE
.PP

.SS "void \fBStock_Write_Dynspec_Data_Part::writeDynspecData\fP (Group &dynspec_grp, std::stringpathDir, std::stringobsName, std::stringpathFile, std::stringoutputFile, File &root_grp, inti, intj, intk, intl, intq, intobsNofStockes, std::vector< std::string >stokesComponent, floatmemoryRAM, intSAPindex, floattimeMinSelect, floattimeMaxSelect, floattimeRebin, floatfrequencyMin, floatfrequencyMax, floatfrequencyRebin)"
.br
 Usage: 
.br
 void Stock_Write_Dynspec_Data_Part::writeDynspecData(Group &dynspec_grp,string pathDir,string obsName,string pathFile,string outputFile,File &root_grp,int i,int j,int k,int l,int q,int obsNofStockes,vector<string> stokesComponent,float memoryRAM, int SAPindex,float timeMinSelect,float timeMaxSelect,float timeRebin,float frequencyMin,float frequencyMax,float frequencyRebin) 
.PP
\fBParameters:\fP
.RS 4
\fI&dynspec_grp\fP Group Object(Dynamic spectrum object) 
.br
\fIpathDir\fP ICD3 path directory 
.br
\fIobsName\fP Observation ID 
.br
\fIpathFile\fP ICD3 path for loading file 
.br
\fIoutputFile\fP output file 
.br
\fI&root_grp\fP File Object (Root Group object) 
.br
\fIi\fP Subarray pointing loop index 
.br
\fIj\fP Beams loop index 
.br
\fIk\fP loop index 
.br
\fIl\fP loop index 
.br
\fIq\fP Pxx nomenclature loop index 
.br
\fIobsNofStockes\fP number of Stokes components 
.br
\fIstokesComponent\fP vector which contains all Stokes components 
.br
\fImemoryRAM\fP RAM memory consuption by processing 
.br
\fISAPindex\fP Subarray pointings to process 
.br
\fItimeMinSelect\fP time minimum selected 
.br
\fItimeMaxSelect\fP time maximum selected 
.br
\fItimeRebin\fP time binning 
.br
\fIfrequencyMin\fP frequency minimum selected 
.br
\fIfrequencyMax\fP frequency maximum selected 
.br
\fIfrequencyRebin\fP frequency binning 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for LOFAR-ICD3 Convertor with selection and/or rebinning from the source code\&.
