% Matlab equivalent of the C++ test program tNoiseTransfer. It generates an
% output file tNoiseTransfer.m.out, which should be identical to the output file
% tNoiseTransfer.out that is generated by the C++ test program.
function tNoiseTransfer()

g = -0.01:0.02:1.18;
fid=fopen('tNoiseTransfer.m.out','w');
for i=1:max(size(g))
    gi = ones(1,60) .* g(i);
    Hn = compute_Hn60(gi);
    if (Hn > 0)
        fprintf(fid, '%s(%0.2f) = %12.8f\n', 'noiseTransfer', g(i), Hn(i));
    end
end
fclose(fid);
