.TH "Reader_Dyn2Dyn_Part" 3 "Thu Jan 10 2013" "LOFAR-ICD6 Convertor with selection and/or rebinning" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Reader_Dyn2Dyn_Part \- 
.PP
Class object for read ICD6 files and put in variables (of metadatas) for the ICD6's Dynspec Group\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Reader_Dyn2Dyn_Part\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBreadDynspec\fP (std::string pathFile, \fBStock_Write_Dyn2Dyn_Metadata_Part\fP *dynspecMetadata, \fBStock_Write_Dyn2Dyn_Data_Part\fP *dynspecData, int j, int obsNofStockes, std::vector< std::string > stokesComponent, float timeMinSelect, float timeMaxSelect, float timeRebin, float frequencyMin, float frequencyMax, float frequencyRebin)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class object for read ICD6 files and put in variables (of metadatas) for the ICD6's Dynspec Group\&. 


.br
 Usage: 
.br
 This class need as parameter a \fBStock_Write_Dyn2Dyn_Metadata_Part\fP object\&. The readDynspec function will read dynspec metadatas and stock them in the \fBStock_Write_Dyn2Dyn_Metadata_Part\fP object as private attributes\&. These attributes will be written in the next step by stocDynspectMetadata function which is in the class \fBStock_Write_Dyn2Dyn_Metadata_Part\&.h\fP In fact this class is very similar to \fBReader_Root_Dyn2Dyn_Part\fP class, the only difference is: this class is for dynspec metadata, so, the main code (\fBDyn2Dyn\&.cpp\fP) loop on dynspec to process and use this class several times (at the opposite of \fBReader_Root_Dyn2Dyn_Part\fP class which is called only once) 
.SH "Member Function Documentation"
.PP 
.SS "void \fBReader_Dyn2Dyn_Part::readDynspec\fP (std::stringpathFile, \fBStock_Write_Dyn2Dyn_Metadata_Part\fP *dynspecMetadata, \fBStock_Write_Dyn2Dyn_Data_Part\fP *dynspecData, intj, intobsNofStockes, std::vector< std::string >stokesComponent, floattimeMinSelect, floattimeMaxSelect, floattimeRebin, floatfrequencyMin, floatfrequencyMax, floatfrequencyRebin)"
.br
 Usage: 
.br
 void Reader_Dyn2Dyn_Part::readDynspec(string pathFile,Stock_Write_Dyn2Dyn_Metadata_Part *dynspecMetadata,Stock_Write_Dyn2Dyn_Data_Part *dynspecData,int j,int obsNofStockes,vector<string> stokesComponent, float timeMinSelect,float timeMaxSelect,float timeRebin,float frequencyMin,float frequencyMax,float frequencyRebin)
.PP
\fBParameters:\fP
.RS 4
\fIpathFile\fP ICD6 (dynamic spectrum) file to read 
.br
\fI*dynspecMetadata\fP \fBReader_Dyn2Dyn_Part\fP Object for loading dynspec metadata in private attributes 
.br
\fI*dynspecData\fP \fBStock_Write_Dyn2Dyn_Data_Part\fP Object for loading new rebinning for data matrix processing 
.br
\fIj\fP loop index on Beams 
.br
\fIobsNofStocke\fP number of Stokes parameter 
.br
\fIstokesComponent\fP vector with Stokes component 
.br
\fISAPindex\fP Index of the SAP in current processing 
.br
\fItimeMinSelect\fP minimum time selection 
.br
\fItimeMaxSelect\fP maximum time selection 
.br
\fItimeRebin\fP time rebinning 
.br
\fIfrequencyMin\fP minimum frequency selection 
.br
\fIfrequencyMax\fP maximum frequency selection 
.br
\fIfrequencyRebin\fP frequency rebinning
.RE
.PP
\fBReturns:\fP
.RS 4
nothing 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for LOFAR-ICD6 Convertor with selection and/or rebinning from the source code\&.
