#!/bin/csh -f
#
# This script simply starts the interactive PyBDSM 
# IPython shell.
#
# Check whether called from CEPI/II. If so, init
# the Python libraries before calling PyBDSM.
if ( $?APS_LOCAL == 0 ) then
    exec python $LOFARSOFT/release/lib/python/bdsm/pybdsm.py 
else
    source ${APS_LOCAL}/login/alias
    use Pythonlibs
    exec python $LOFARSOFT/release/lib/python/bdsm/pybdsm.py
endif
