# $Id: makefile,v 1.4 2006/10/19 08:32:18 bahren Exp $

OPT:=2

# Use the generic AIPS++ test makefile.
#--------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.tst
