#! /bin/bash

dir=`dirname $0`
export LD_LIBRARY_PATH=/opt/LofIm/daily/pyrap/lib:/opt/LofIm/daily/casacore/lib:/opt/hdf5/lib:/opt/LofIm/daily/lofar/lib
export PYTHONPATH=/opt/LofIm/daily/pyrap/lib:${dir}
${dir}/msinfo.py $@
