//see hfpp.h
//#define HFPP_VEC_WRAPPER_CODE_STL_DEFAULT return HFPP_FUNCNAME(HFPP_PAR_VECTORITERATORS(STL) HFPP_PAR_PARAMETERS_COMMA)
//#define HFPP_VEC_WRAPPER_CODE_CASA_DEFAULT return HFPP_FUNCNAME(HFPP_PAR_VECTORITERATORS(CASA) HFPP_PAR_PARAMETERS_COMMA)
#ifdef HFPP_ALT_FUNCNAME
#line BOOST_PP_LINE(__LINE__,HFPP_ALT_FUNCNAME)
#undef  HFPP_VEC_WRAPPER_CODE_STL 
#define HFPP_VEC_WRAPPER_CODE_STL HFPP_VEC_WRAPPER_CODE_STL_DEFAULT(HFPP_ALT_FUNCNAME)
#undef  HFPP_VEC_WRAPPER_CODE_CASA 
#define HFPP_VEC_WRAPPER_CODE_CASA HFPP_VEC_WRAPPER_CODE_CASA_DEFAULT(HFPP_ALT_FUNCNAME)
#undef  HFPP_VEC_WRAPPER_CODE_GUI 
#define HFPP_VEC_WRAPPER_CODE_GUI HFPP_VEC_WRAPPER_CODE_GUI_DEFAULT(HFPP_ALT_FUNCNAME)
#else
#line BOOST_PP_LINE(__LINE__,HFPP_FUNCNAME)
#undef  HFPP_VEC_WRAPPER_CODE_STL 
#define HFPP_VEC_WRAPPER_CODE_STL HFPP_VEC_WRAPPER_CODE_STL_DEFAULT(HFPP_FUNCNAME)
#undef  HFPP_VEC_WRAPPER_CODE_CASA 
#define HFPP_VEC_WRAPPER_CODE_CASA HFPP_VEC_WRAPPER_CODE_CASA_DEFAULT(HFPP_FUNCNAME)
#undef  HFPP_VEC_WRAPPER_CODE_GUI 
#define HFPP_VEC_WRAPPER_CODE_GUI HFPP_VEC_WRAPPER_CODE_GUI_DEFAULT(HFPP_FUNCNAME)
#endif
HFPP_GENERATE_WRAPPERS
