# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hfgui2.ui'
#
# Created: Wed Feb  4 14:19:18 2009
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1127, 664)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(720, -30, 75, 24))
        self.pushButton.setObjectName("pushButton")
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 5, 1121, 611))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_3 = QtGui.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(335, 5, 781, 536))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.tabwindow = QtGui.QTabWidget(self.frame_3)
        self.tabwindow.setGeometry(QtCore.QRect(5, 0, 771, 531))
        self.tabwindow.setObjectName("tabwindow")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.HMainPlotter = hfQtPlotWidget(self.tab)
        self.HMainPlotter.setGeometry(QtCore.QRect(0, 0, 766, 511))
        self.HMainPlotter.setBaseSize(QtCore.QSize(800, 600))
        self.HMainPlotter.setObjectName("HMainPlotter")
        self.tabwindow.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.networkdisplay = QtSvg.QSvgWidget(self.tab_2)
        self.networkdisplay.setGeometry(QtCore.QRect(0, 0, 766, 506))
        self.networkdisplay.setObjectName("networkdisplay")
        self.tabwindow.addTab(self.tab_2, "")
        self.frame_4 = QtGui.QFrame(self.frame)
        self.frame_4.setGeometry(QtCore.QRect(5, 0, 326, 601))
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.widget = QtGui.QWidget(self.frame_4)
        self.widget.setGeometry(QtCore.QRect(0, 0, 321, 601))
        self.widget.setObjectName("widget")
        self.frame_7 = QtGui.QFrame(self.widget)
        self.frame_7.setGeometry(QtCore.QRect(0, 0, 321, 591))
        self.frame_7.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.frame_12 = QtGui.QFrame(self.frame_7)
        self.frame_12.setGeometry(QtCore.QRect(3, 415, 306, 66))
        self.frame_12.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.frame_13 = QtGui.QFrame(self.frame_12)
        self.frame_13.setGeometry(QtCore.QRect(0, 0, 301, 31))
        self.frame_13.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_13.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.label_5 = QtGui.QLabel(self.frame_13)
        self.label_5.setGeometry(QtCore.QRect(10, 0, 81, 20))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.windowselection = QtGui.QComboBox(self.frame_13)
        self.windowselection.setGeometry(QtCore.QRect(120, 0, 171, 26))
        self.windowselection.setEditable(False)
        self.windowselection.setObjectName("windowselection")
        self.windowselection.addItem(QtCore.QString())
        self.windowselection.addItem(QtCore.QString())
        self.frame_14 = QtGui.QFrame(self.frame_12)
        self.frame_14.setGeometry(QtCore.QRect(0, 30, 301, 20))
        self.frame_14.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_14.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.label_7 = QtGui.QLabel(self.frame_14)
        self.label_7.setGeometry(QtCore.QRect(0, 0, 81, 21))
        self.label_7.setObjectName("label_7")
        self.npanels = QtGui.QLineEdit(self.frame_14)
        self.npanels.setGeometry(QtCore.QRect(70, 0, 21, 22))
        self.npanels.setObjectName("npanels")
        self.npanelsx = QtGui.QLineEdit(self.frame_14)
        self.npanelsx.setGeometry(QtCore.QRect(160, 0, 21, 22))
        self.npanelsx.setObjectName("npanelsx")
        self.panelauto = QtGui.QCheckBox(self.frame_14)
        self.panelauto.setGeometry(QtCore.QRect(240, 0, 51, 21))
        self.panelauto.setObjectName("panelauto")
        self.label_8 = QtGui.QLabel(self.frame_14)
        self.label_8.setGeometry(QtCore.QRect(90, 0, 71, 17))
        self.label_8.setObjectName("label_8")
        self.npanelsy = QtGui.QLineEdit(self.frame_14)
        self.npanelsy.setGeometry(QtCore.QRect(210, 0, 21, 22))
        self.npanelsy.setObjectName("npanelsy")
        self.label_9 = QtGui.QLabel(self.frame_14)
        self.label_9.setGeometry(QtCore.QRect(190, 0, 16, 17))
        self.label_9.setObjectName("label_9")
        self.frame_5 = QtGui.QFrame(self.frame_7)
        self.frame_5.setEnabled(True)
        self.frame_5.setGeometry(QtCore.QRect(5, 5, 306, 111))
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 282))
        self.frame_5.setCursor(QtCore.Qt.ArrowCursor)
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.commandLinkButton = QtGui.QCommandLinkButton(self.frame_5)
        self.commandLinkButton.setGeometry(QtCore.QRect(215, 80, 91, 31))
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.frame_6 = QtGui.QFrame(self.frame_5)
        self.frame_6.setGeometry(QtCore.QRect(0, 0, 301, 31))
        self.frame_6.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label = QtGui.QLabel(self.frame_6)
        self.label.setGeometry(QtCore.QRect(10, 0, 101, 20))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.plotterselection = QtGui.QComboBox(self.frame_6)
        self.plotterselection.setGeometry(QtCore.QRect(120, 0, 171, 26))
        self.plotterselection.setEditable(False)
        self.plotterselection.setObjectName("plotterselection")
        self.plotterselection.addItem(QtCore.QString())
        self.plotterselection.addItem(QtCore.QString())
        self.plotterselection.addItem(QtCore.QString())
        self.plotterselection.addItem(QtCore.QString())
        self.plotterselection.addItem(QtCore.QString())
        self.frame_9 = QtGui.QFrame(self.frame_5)
        self.frame_9.setGeometry(QtCore.QRect(0, 30, 291, 16))
        self.frame_9.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.label_6 = QtGui.QLabel(self.frame_9)
        self.label_6.setGeometry(QtCore.QRect(0, 0, 41, 16))
        self.label_6.setObjectName("label_6")
        self.color = QtGui.QLineEdit(self.frame_9)
        self.color.setGeometry(QtCore.QRect(40, 0, 21, 16))
        self.color.setObjectName("color")
        self.xdatatype = QtGui.QComboBox(self.frame_5)
        self.xdatatype.setGeometry(QtCore.QRect(0, 50, 111, 26))
        self.xdatatype.setEditable(True)
        self.xdatatype.setObjectName("xdatatype")
        self.ydatatype = QtGui.QComboBox(self.frame_5)
        self.ydatatype.setGeometry(QtCore.QRect(120, 50, 111, 26))
        self.ydatatype.setEditable(True)
        self.ydatatype.setObjectName("ydatatype")
        self.frame_15 = QtGui.QFrame(self.frame_7)
        self.frame_15.setGeometry(QtCore.QRect(0, 235, 311, 106))
        self.frame_15.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.frame_10 = QtGui.QFrame(self.frame_15)
        self.frame_10.setGeometry(QtCore.QRect(5, 55, 271, 21))
        self.frame_10.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_10.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.label_2 = QtGui.QLabel(self.frame_10)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 71, 21))
        self.label_2.setObjectName("label_2")
        self.ymin = QtGui.QLineEdit(self.frame_10)
        self.ymin.setGeometry(QtCore.QRect(60, 0, 71, 22))
        self.ymin.setObjectName("ymin")
        self.ymax = QtGui.QLineEdit(self.frame_10)
        self.ymax.setGeometry(QtCore.QRect(140, 0, 71, 22))
        self.ymax.setObjectName("ymax")
        self.yauto = QtGui.QCheckBox(self.frame_10)
        self.yauto.setGeometry(QtCore.QRect(220, 0, 51, 21))
        self.yauto.setObjectName("yauto")
        self.frame_11 = QtGui.QFrame(self.frame_15)
        self.frame_11.setGeometry(QtCore.QRect(0, 0, 301, 31))
        self.frame_11.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_11.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.label_4 = QtGui.QLabel(self.frame_11)
        self.label_4.setGeometry(QtCore.QRect(10, 0, 41, 20))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.panelselection = QtGui.QComboBox(self.frame_11)
        self.panelselection.setGeometry(QtCore.QRect(120, 0, 171, 26))
        self.panelselection.setEditable(False)
        self.panelselection.setObjectName("panelselection")
        self.panelselection.addItem(QtCore.QString())
        self.panelselection.addItem(QtCore.QString())
        self.panelselection.addItem(QtCore.QString())
        self.frame_8 = QtGui.QFrame(self.frame_15)
        self.frame_8.setGeometry(QtCore.QRect(5, 30, 271, 21))
        self.frame_8.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_8.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.label_3 = QtGui.QLabel(self.frame_8)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 71, 21))
        self.label_3.setObjectName("label_3")
        self.xmin = QtGui.QLineEdit(self.frame_8)
        self.xmin.setGeometry(QtCore.QRect(60, 0, 71, 22))
        self.xmin.setObjectName("xmin")
        self.xmax = QtGui.QLineEdit(self.frame_8)
        self.xmax.setGeometry(QtCore.QRect(140, 0, 71, 22))
        self.xmax.setObjectName("xmax")
        self.xauto = QtGui.QCheckBox(self.frame_8)
        self.xauto.setGeometry(QtCore.QRect(220, 0, 51, 21))
        self.xauto.setObjectName("xauto")
        self.quit = QtGui.QPushButton(self.frame_7)
        self.quit.setGeometry(QtCore.QRect(245, 560, 75, 24))
        self.quit.setObjectName("quit")
        self.replot = QtGui.QPushButton(self.frame_7)
        self.replot.setGeometry(QtCore.QRect(5, 560, 75, 24))
        self.replot.setObjectName("replot")
        self.frame_16 = QtGui.QFrame(self.frame_7)
        self.frame_16.setGeometry(QtCore.QRect(5, 510, 306, 26))
        self.frame_16.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.label_10 = QtGui.QLabel(self.frame_16)
        self.label_10.setGeometry(QtCore.QRect(10, 5, 156, 17))
        self.label_10.setObjectName("label_10")
        self.netlevel = QtGui.QComboBox(self.frame_16)
        self.netlevel.setGeometry(QtCore.QRect(180, 0, 111, 26))
        self.netlevel.setEditable(True)
        self.netlevel.setObjectName("netlevel")
        self.netlevel.addItem(QtCore.QString())
        self.netlevel.addItem(QtCore.QString())
        self.netlevel.addItem(QtCore.QString())
        self.frame_2 = QtGui.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(335, 545, 781, 61))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1127, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabwindow.setCurrentIndex(0)
        QtCore.QObject.connect(self.npanels, QtCore.SIGNAL("returnPressed()"), self.HMainPlotter.hfsetNPanels)
        QtCore.QObject.connect(self.quit, QtCore.SIGNAL("clicked()"), MainWindow.close)
        QtCore.QObject.connect(self.replot, QtCore.SIGNAL("clicked()"), self.HMainPlotter.repaint)
        QtCore.QObject.connect(self.npanelsx, QtCore.SIGNAL("returnPressed()"), self.HMainPlotter.hfsetNPanelsx)
        QtCore.QObject.connect(self.npanelsy, QtCore.SIGNAL("returnPressed()"), self.HMainPlotter.hfsetNPanelsy)
        QtCore.QObject.connect(self.xmin, QtCore.SIGNAL("returnPressed()"), self.HMainPlotter.hfsetXMin)
        QtCore.QObject.connect(self.xmax, QtCore.SIGNAL("returnPressed()"), self.HMainPlotter.hfsetXMax)
        QtCore.QObject.connect(self.ymin, QtCore.SIGNAL("returnPressed()"), self.HMainPlotter.hfsetYMin)
        QtCore.QObject.connect(self.ymax, QtCore.SIGNAL("returnPressed()"), self.HMainPlotter.hfsetYMax)
        QtCore.QObject.connect(self.xdatatype, QtCore.SIGNAL("textChanged(QString)"), self.HMainPlotter.xdatatype)
        QtCore.QObject.connect(self.netlevel, QtCore.SIGNAL("textChanged(QString)"), self.HMainPlotter.netlevel)
        QtCore.QObject.connect(self.ydatatype, QtCore.SIGNAL("textChanged(QString)"), self.HMainPlotter.ydatatype)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.tabwindow.setTabText(self.tabwindow.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Tab 1", None, QtGui.QApplication.UnicodeUTF8))
        self.tabwindow.setTabText(self.tabwindow.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Tab 2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Window:", None, QtGui.QApplication.UnicodeUTF8))
        self.windowselection.setItemText(0, QtGui.QApplication.translate("MainWindow", "All Windows", None, QtGui.QApplication.UnicodeUTF8))
        self.windowselection.setItemText(1, QtGui.QApplication.translate("MainWindow", "Window 1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "No. Panels:", None, QtGui.QApplication.UnicodeUTF8))
        self.panelauto.setText(QtGui.QApplication.translate("MainWindow", "Auto", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", " row x col:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.commandLinkButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Provides access to all parameters of DataPlotter", None, QtGui.QApplication.UnicodeUTF8))
        self.commandLinkButton.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Provides access to all parameters of DataPlotter", None, QtGui.QApplication.UnicodeUTF8))
        self.commandLinkButton.setText(QtGui.QApplication.translate("MainWindow", "Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Data Plotter:", None, QtGui.QApplication.UnicodeUTF8))
        self.plotterselection.setItemText(0, QtGui.QApplication.translate("MainWindow", "Selected Window", None, QtGui.QApplication.UnicodeUTF8))
        self.plotterselection.setItemText(1, QtGui.QApplication.translate("MainWindow", "Selected Panel", None, QtGui.QApplication.UnicodeUTF8))
        self.plotterselection.setItemText(2, QtGui.QApplication.translate("MainWindow", "All Lines", None, QtGui.QApplication.UnicodeUTF8))
        self.plotterselection.setItemText(3, QtGui.QApplication.translate("MainWindow", "Line 1", None, QtGui.QApplication.UnicodeUTF8))
        self.plotterselection.setItemText(4, QtGui.QApplication.translate("MainWindow", "Line 2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Color:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "y-Range:", None, QtGui.QApplication.UnicodeUTF8))
        self.yauto.setText(QtGui.QApplication.translate("MainWindow", "Auto", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Panel:", None, QtGui.QApplication.UnicodeUTF8))
        self.panelselection.setItemText(0, QtGui.QApplication.translate("MainWindow", "Selected Windows", None, QtGui.QApplication.UnicodeUTF8))
        self.panelselection.setItemText(1, QtGui.QApplication.translate("MainWindow", "All Panels", None, QtGui.QApplication.UnicodeUTF8))
        self.panelselection.setItemText(2, QtGui.QApplication.translate("MainWindow", "Panel 1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "x-Range:", None, QtGui.QApplication.UnicodeUTF8))
        self.xauto.setText(QtGui.QApplication.translate("MainWindow", "Auto", None, QtGui.QApplication.UnicodeUTF8))
        self.quit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.replot.setText(QtGui.QApplication.translate("MainWindow", "Replot", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Network Display Level:", None, QtGui.QApplication.UnicodeUTF8))
        self.netlevel.setItemText(0, QtGui.QApplication.translate("MainWindow", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.netlevel.setItemText(1, QtGui.QApplication.translate("MainWindow", "99", None, QtGui.QApplication.UnicodeUTF8))
        self.netlevel.setItemText(2, QtGui.QApplication.translate("MainWindow", "999", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))

