# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hfgui2.ui'
#
# Created: Wed Dec  2 11:01:49 2009
#      by: PyQt4 UI code generator 4.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1126, 669)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(720, -30, 75, 24))
        self.pushButton.setObjectName("pushButton")
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 5, 1121, 623))
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_3 = QtGui.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(335, 5, 777, 499))
        self.frame_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.tabwindow = QtGui.QTabWidget(self.frame_3)
        self.tabwindow.setGeometry(QtCore.QRect(5, 0, 769, 493))
        self.tabwindow.setObjectName("tabwindow")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.HMainPlotter = hfQtPlotWidget(self.tab)
        self.HMainPlotter.setGeometry(QtCore.QRect(0, 0, 763, 461))
        self.HMainPlotter.setBaseSize(QtCore.QSize(765, 510))
        self.HMainPlotter.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.HMainPlotter.setObjectName("HMainPlotter")
        self.tabwindow.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.networkscrollarea = QtGui.QScrollArea(self.tab_2)
        self.networkscrollarea.setGeometry(QtCore.QRect(22, 20, 733, 439))
        self.networkscrollarea.setWidgetResizable(False)
        self.networkscrollarea.setObjectName("networkscrollarea")
        self.scrollAreaWidgetContents = QtGui.QWidget(self.networkscrollarea)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 763, 495))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.networkdisplay = QtSvg.QSvgWidget(self.scrollAreaWidgetContents)
        self.networkdisplay.setGeometry(QtCore.QRect(0, 32, 711, 421))
        self.networkdisplay.setObjectName("networkdisplay")
        self.networkscrollarea.setWidget(self.scrollAreaWidgetContents)
        self.networkzoom = QtGui.QSlider(self.tab_2)
        self.networkzoom.setGeometry(QtCore.QRect(2, 22, 22, 471))
        self.networkzoom.setMinimum(-50)
        self.networkzoom.setMaximum(50)
        self.networkzoom.setOrientation(QtCore.Qt.Vertical)
        self.networkzoom.setInvertedAppearance(False)
        self.networkzoom.setInvertedControls(False)
        self.networkzoom.setObjectName("networkzoom")
        self.networkaspectslider = QtGui.QSlider(self.tab_2)
        self.networkaspectslider.setGeometry(QtCore.QRect(24, -2, 727, 22))
        self.networkaspectslider.setMinimum(-50)
        self.networkaspectslider.setMaximum(50)
        self.networkaspectslider.setOrientation(QtCore.Qt.Horizontal)
        self.networkaspectslider.setObjectName("networkaspectslider")
        self.tabwindow.addTab(self.tab_2, "")
        self.frame_4 = QtGui.QFrame(self.frame)
        self.frame_4.setGeometry(QtCore.QRect(5, -8, 326, 627))
        self.frame_4.setAutoFillBackground(True)
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.widget = QtGui.QWidget(self.frame_4)
        self.widget.setGeometry(QtCore.QRect(0, 20, 327, 663))
        self.widget.setAutoFillBackground(True)
        self.widget.setObjectName("widget")
        self.frame_7 = QtGui.QFrame(self.widget)
        self.frame_7.setGeometry(QtCore.QRect(-2, 4, 329, 573))
        self.frame_7.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.frame_12 = QtGui.QFrame(self.frame_7)
        self.frame_12.setGeometry(QtCore.QRect(3, 394, 317, 57))
        self.frame_12.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_12.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.frame_14 = QtGui.QFrame(self.frame_12)
        self.frame_14.setGeometry(QtCore.QRect(0, 30, 315, 20))
        self.frame_14.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_14.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.label_7 = QtGui.QLabel(self.frame_14)
        self.label_7.setGeometry(QtCore.QRect(8, 0, 59, 21))
        self.label_7.setObjectName("label_7")
        self.npanels = QtGui.QLineEdit(self.frame_14)
        self.npanels.setGeometry(QtCore.QRect(70, 0, 21, 22))
        self.npanels.setObjectName("npanels")
        self.npanelsx = QtGui.QLineEdit(self.frame_14)
        self.npanelsx.setGeometry(QtCore.QRect(160, 0, 21, 22))
        self.npanelsx.setObjectName("npanelsx")
        self.panelauto = QtGui.QCheckBox(self.frame_14)
        self.panelauto.setGeometry(QtCore.QRect(260, 0, 51, 21))
        self.panelauto.setObjectName("panelauto")
        self.label_8 = QtGui.QLabel(self.frame_14)
        self.label_8.setGeometry(QtCore.QRect(90, 0, 71, 17))
        self.label_8.setObjectName("label_8")
        self.npanelsy = QtGui.QLineEdit(self.frame_14)
        self.npanelsy.setGeometry(QtCore.QRect(210, 0, 21, 22))
        self.npanelsy.setObjectName("npanelsy")
        self.label_9 = QtGui.QLabel(self.frame_14)
        self.label_9.setGeometry(QtCore.QRect(190, 0, 16, 17))
        self.label_9.setObjectName("label_9")
        self.frame_5 = QtGui.QFrame(self.frame_7)
        self.frame_5.setEnabled(True)
        self.frame_5.setGeometry(QtCore.QRect(6, 0, 315, 111))
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 282))
        self.frame_5.setCursor(QtCore.Qt.ArrowCursor)
        self.frame_5.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.frame_9 = QtGui.QFrame(self.frame_5)
        self.frame_9.setGeometry(QtCore.QRect(0, 28, 305, 16))
        self.frame_9.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_9.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.label_6 = QtGui.QLabel(self.frame_9)
        self.label_6.setGeometry(QtCore.QRect(0, 0, 65, 16))
        self.label_6.setObjectName("label_6")
        self.firstantenna = QtGui.QLineEdit(self.frame_9)
        self.firstantenna.setGeometry(QtCore.QRect(62, 0, 21, 16))
        self.firstantenna.setObjectName("firstantenna")
        self.label_23 = QtGui.QLabel(self.frame_9)
        self.label_23.setGeometry(QtCore.QRect(84, 0, 16, 16))
        self.label_23.setObjectName("label_23")
        self.lastantenna = QtGui.QLineEdit(self.frame_9)
        self.lastantenna.setGeometry(QtCore.QRect(94, 0, 21, 16))
        self.lastantenna.setObjectName("lastantenna")
        self.antennaselection = QtGui.QLineEdit(self.frame_9)
        self.antennaselection.setGeometry(QtCore.QRect(132, -2, 173, 22))
        self.antennaselection.setObjectName("antennaselection")
        self.xdatatype = QtGui.QComboBox(self.frame_5)
        self.xdatatype.setGeometry(QtCore.QRect(58, 48, 111, 26))
        self.xdatatype.setEditable(True)
        self.xdatatype.setObjectName("xdatatype")
        self.ydatatype = QtGui.QComboBox(self.frame_5)
        self.ydatatype.setGeometry(QtCore.QRect(58, 72, 111, 26))
        self.ydatatype.setEditable(True)
        self.ydatatype.setObjectName("ydatatype")
        self.label_15 = QtGui.QLabel(self.frame_5)
        self.label_15.setGeometry(QtCore.QRect(2, 52, 61, 17))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtGui.QLabel(self.frame_5)
        self.label_16.setGeometry(QtCore.QRect(2, 76, 61, 17))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtGui.QLabel(self.frame_5)
        self.label_17.setGeometry(QtCore.QRect(176, 52, 31, 17))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtGui.QLabel(self.frame_5)
        self.label_18.setGeometry(QtCore.QRect(258, 50, 43, 17))
        self.label_18.setObjectName("label_18")
        self.xaxisunit = QtGui.QComboBox(self.frame_5)
        self.xaxisunit.setGeometry(QtCore.QRect(206, 46, 55, 26))
        self.xaxisunit.setEditable(True)
        self.xaxisunit.setFrame(False)
        self.xaxisunit.setObjectName("xaxisunit")
        self.label_19 = QtGui.QLabel(self.frame_5)
        self.label_19.setGeometry(QtCore.QRect(176, 76, 31, 17))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtGui.QLabel(self.frame_5)
        self.label_20.setGeometry(QtCore.QRect(258, 74, 43, 17))
        self.label_20.setObjectName("label_20")
        self.yaxisunit = QtGui.QComboBox(self.frame_5)
        self.yaxisunit.setGeometry(QtCore.QRect(206, 70, 55, 26))
        self.yaxisunit.setEditable(True)
        self.yaxisunit.setObjectName("yaxisunit")
        self.logx = QtGui.QCheckBox(self.frame_5)
        self.logx.setGeometry(QtCore.QRect(260, 50, 43, 21))
        self.logx.setObjectName("logx")
        self.logy = QtGui.QCheckBox(self.frame_5)
        self.logy.setGeometry(QtCore.QRect(260, 74, 43, 21))
        self.logy.setObjectName("logy")
        self.frame_15 = QtGui.QFrame(self.frame_7)
        self.frame_15.setGeometry(QtCore.QRect(0, 232, 321, 101))
        self.frame_15.setAutoFillBackground(False)
        self.frame_15.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_15.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.frame_10 = QtGui.QFrame(self.frame_15)
        self.frame_10.setGeometry(QtCore.QRect(1, 50, 319, 51))
        self.frame_10.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_10.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.label_2 = QtGui.QLabel(self.frame_10)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 47, 21))
        self.label_2.setObjectName("label_2")
        self.ymin = QtGui.QLineEdit(self.frame_10)
        self.ymin.setGeometry(QtCore.QRect(62, 10, 71, 22))
        self.ymin.setObjectName("ymin")
        self.ymax = QtGui.QLineEdit(self.frame_10)
        self.ymax.setGeometry(QtCore.QRect(142, 10, 71, 22))
        self.ymax.setObjectName("ymax")
        self.yauto = QtGui.QCheckBox(self.frame_10)
        self.yauto.setGeometry(QtCore.QRect(222, 0, 57, 21))
        self.yauto.setChecked(True)
        self.yauto.setObjectName("yauto")
        self.yzoomdial = QtGui.QDial(self.frame_10)
        self.yzoomdial.setGeometry(QtCore.QRect(278, 0, 40, 40))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(67, 255, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(179, 255, 168))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(123, 255, 104))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(33, 127, 20))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(44, 170, 26))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(67, 255, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(161, 255, 147))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(67, 255, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(179, 255, 168))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(123, 255, 104))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(33, 127, 20))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(44, 170, 26))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(67, 255, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(161, 255, 147))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        brush = QtGui.QBrush(QtGui.QColor(33, 127, 20))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(67, 255, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(179, 255, 168))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(123, 255, 104))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(33, 127, 20))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(44, 170, 26))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(33, 127, 20))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(33, 127, 20))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(67, 255, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(67, 255, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(67, 255, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.yzoomdial.setPalette(palette)
        self.yzoomdial.setMinimum(-10)
        self.yzoomdial.setMaximum(100)
        self.yzoomdial.setWrapping(False)
        self.yzoomdial.setNotchTarget(4.0)
        self.yzoomdial.setNotchesVisible(True)
        self.yzoomdial.setObjectName("yzoomdial")
        self.yshiftslider = QtGui.QSlider(self.frame_10)
        self.yshiftslider.setGeometry(QtCore.QRect(6, 30, 307, 22))
        self.yshiftslider.setMinimum(-100)
        self.yshiftslider.setMaximum(100)
        self.yshiftslider.setOrientation(QtCore.Qt.Horizontal)
        self.yshiftslider.setObjectName("yshiftslider")
        self.frame_21 = QtGui.QFrame(self.frame_10)
        self.frame_21.setGeometry(QtCore.QRect(222, 18, 53, 19))
        self.frame_21.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_21.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.label_14 = QtGui.QLabel(self.frame_21)
        self.label_14.setGeometry(QtCore.QRect(18, 2, 39, 17))
        self.label_14.setObjectName("label_14")
        self.yreset = QtGui.QPushButton(self.frame_21)
        self.yreset.setGeometry(QtCore.QRect(2, 2, 14, 14))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.yreset.setFont(font)
        self.yreset.setObjectName("yreset")
        self.frame_8 = QtGui.QFrame(self.frame_15)
        self.frame_8.setGeometry(QtCore.QRect(1, 0, 319, 51))
        self.frame_8.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_8.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.label_3 = QtGui.QLabel(self.frame_8)
        self.label_3.setGeometry(QtCore.QRect(8, 8, 53, 21))
        self.label_3.setObjectName("label_3")
        self.xmin = QtGui.QLineEdit(self.frame_8)
        self.xmin.setGeometry(QtCore.QRect(62, 8, 71, 22))
        self.xmin.setObjectName("xmin")
        self.xmax = QtGui.QLineEdit(self.frame_8)
        self.xmax.setGeometry(QtCore.QRect(142, 8, 71, 22))
        self.xmax.setObjectName("xmax")
        self.xauto = QtGui.QCheckBox(self.frame_8)
        self.xauto.setGeometry(QtCore.QRect(222, 0, 51, 21))
        self.xauto.setChecked(True)
        self.xauto.setObjectName("xauto")
        self.xzoomdial = QtGui.QDial(self.frame_8)
        self.xzoomdial.setGeometry(QtCore.QRect(278, 0, 40, 40))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(67, 255, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(179, 255, 168))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(123, 255, 104))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(33, 127, 20))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(44, 170, 26))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(67, 255, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(161, 255, 147))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(67, 255, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(179, 255, 168))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(123, 255, 104))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(33, 127, 20))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(44, 170, 26))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(67, 255, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(161, 255, 147))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        brush = QtGui.QBrush(QtGui.QColor(33, 127, 20))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(67, 255, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(179, 255, 168))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(123, 255, 104))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(33, 127, 20))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(44, 170, 26))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(33, 127, 20))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(33, 127, 20))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(67, 255, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(67, 255, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(67, 255, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.xzoomdial.setPalette(palette)
        self.xzoomdial.setMinimum(-10)
        self.xzoomdial.setMaximum(100)
        self.xzoomdial.setInvertedAppearance(False)
        self.xzoomdial.setInvertedControls(False)
        self.xzoomdial.setWrapping(False)
        self.xzoomdial.setNotchTarget(4.0)
        self.xzoomdial.setNotchesVisible(True)
        self.xzoomdial.setObjectName("xzoomdial")
        self.xshiftslider = QtGui.QSlider(self.frame_8)
        self.xshiftslider.setGeometry(QtCore.QRect(6, 30, 307, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.xshiftslider.setFont(font)
        self.xshiftslider.setMinimum(-100)
        self.xshiftslider.setMaximum(100)
        self.xshiftslider.setOrientation(QtCore.Qt.Horizontal)
        self.xshiftslider.setObjectName("xshiftslider")
        self.frame_20 = QtGui.QFrame(self.frame_8)
        self.frame_20.setGeometry(QtCore.QRect(222, 18, 51, 19))
        self.frame_20.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_20.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.label_13 = QtGui.QLabel(self.frame_20)
        self.label_13.setGeometry(QtCore.QRect(18, 2, 37, 17))
        self.label_13.setObjectName("label_13")
        self.xreset = QtGui.QPushButton(self.frame_20)
        self.xreset.setGeometry(QtCore.QRect(2, 2, 14, 14))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.xreset.setFont(font)
        self.xreset.setObjectName("xreset")
        self.frame_16 = QtGui.QFrame(self.frame_7)
        self.frame_16.setGeometry(QtCore.QRect(5, 454, 321, 26))
        self.frame_16.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_16.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.label_10 = QtGui.QLabel(self.frame_16)
        self.label_10.setGeometry(QtCore.QRect(210, 2, 41, 20))
        self.label_10.setObjectName("label_10")
        self.netlevel = QtGui.QComboBox(self.frame_16)
        self.netlevel.setGeometry(QtCore.QRect(250, 0, 63, 26))
        self.netlevel.setEditable(True)
        self.netlevel.setObjectName("netlevel")
        self.netlevel.addItem(QtCore.QString())
        self.netlevel.addItem(QtCore.QString())
        self.netlevel.addItem(QtCore.QString())
        self.netlevel.addItem(QtCore.QString())
        self.netlevel.addItem(QtCore.QString())
        self.networkdisplayon = QtGui.QCheckBox(self.frame_16)
        self.networkdisplayon.setGeometry(QtCore.QRect(4, 2, 137, 21))
        self.networkdisplayon.setChecked(False)
        self.networkdisplayon.setObjectName("networkdisplayon")
        self.pushButton_2 = QtGui.QPushButton(self.frame_16)
        self.pushButton_2.setGeometry(QtCore.QRect(134, -2, 53, 32))
        self.pushButton_2.setObjectName("pushButton_2")
        self.frame_23 = QtGui.QFrame(self.frame_7)
        self.frame_23.setGeometry(QtCore.QRect(2, 114, 319, 57))
        self.frame_23.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_23.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.frame_22 = QtGui.QFrame(self.frame_23)
        self.frame_22.setGeometry(QtCore.QRect(4, 30, 309, 25))
        self.frame_22.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_22.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.add_fy = QtGui.QComboBox(self.frame_22)
        self.add_fy.setGeometry(QtCore.QRect(90, 0, 105, 26))
        self.add_fy.setObjectName("add_fy")
        self.remove_fy = QtGui.QPushButton(self.frame_22)
        self.remove_fy.setGeometry(QtCore.QRect(200, -2, 113, 32))
        self.remove_fy.setObjectName("remove_fy")
        self.label_24 = QtGui.QLabel(self.frame_22)
        self.label_24.setGeometry(QtCore.QRect(2, 4, 29, 17))
        self.label_24.setObjectName("label_24")
        self.view_fxchain_2 = QtGui.QPushButton(self.frame_22)
        self.view_fxchain_2.setGeometry(QtCore.QRect(32, -2, 59, 32))
        self.view_fxchain_2.setObjectName("view_fxchain_2")
        self.frame_24 = QtGui.QFrame(self.frame_23)
        self.frame_24.setGeometry(QtCore.QRect(4, 4, 309, 25))
        self.frame_24.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_24.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.add_fx = QtGui.QComboBox(self.frame_24)
        self.add_fx.setGeometry(QtCore.QRect(90, 0, 105, 26))
        self.add_fx.setObjectName("add_fx")
        self.remove_fx = QtGui.QPushButton(self.frame_24)
        self.remove_fx.setGeometry(QtCore.QRect(200, -2, 113, 32))
        self.remove_fx.setObjectName("remove_fx")
        self.label_25 = QtGui.QLabel(self.frame_24)
        self.label_25.setGeometry(QtCore.QRect(2, 4, 29, 17))
        self.label_25.setObjectName("label_25")
        self.view_fxchain = QtGui.QPushButton(self.frame_24)
        self.view_fxchain.setGeometry(QtCore.QRect(32, -2, 59, 32))
        self.view_fxchain.setObjectName("view_fxchain")
        self.frame_18 = QtGui.QFrame(self.frame_7)
        self.frame_18.setGeometry(QtCore.QRect(2, 174, 317, 59))
        self.frame_18.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_18.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.blocknumber = QtGui.QSpinBox(self.frame_18)
        self.blocknumber.setGeometry(QtCore.QRect(170, 18, 143, 26))
        self.blocknumber.setObjectName("blocknumber")
        self.label_11 = QtGui.QLabel(self.frame_18)
        self.label_11.setGeometry(QtCore.QRect(166, 2, 101, 17))
        self.label_11.setObjectName("label_11")
        self.blocknumberslider = QtGui.QSlider(self.frame_18)
        self.blocknumberslider.setGeometry(QtCore.QRect(2, 38, 311, 22))
        self.blocknumberslider.setOrientation(QtCore.Qt.Horizontal)
        self.blocknumberslider.setObjectName("blocknumberslider")
        self.lineEdit = QtGui.QLineEdit(self.frame_18)
        self.lineEdit.setGeometry(QtCore.QRect(170, 20, 123, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.comboBox = QtGui.QComboBox(self.frame_18)
        self.comboBox.setGeometry(QtCore.QRect(8, 18, 159, 26))
        self.comboBox.setEditable(True)
        self.comboBox.setMaxVisibleItems(10)
        self.comboBox.setInsertPolicy(QtGui.QComboBox.InsertAlphabetically)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem(QtCore.QString())
        self.comboBox.addItem(QtCore.QString())
        self.comboBox.addItem(QtCore.QString())
        self.comboBox.addItem(QtCore.QString())
        self.comboBox.addItem(QtCore.QString())
        self.comboBox.addItem(QtCore.QString())
        self.comboBox.addItem(QtCore.QString())
        self.comboBox.addItem(QtCore.QString())
        self.comboBox.addItem(QtCore.QString())
        self.comboBox.addItem(QtCore.QString())
        self.comboBox.addItem(QtCore.QString())
        self.comboBox.addItem(QtCore.QString())
        self.comboBox.addItem(QtCore.QString())
        self.comboBox.addItem(QtCore.QString())
        self.label_12 = QtGui.QLabel(self.frame_18)
        self.label_12.setGeometry(QtCore.QRect(8, 2, 77, 17))
        self.label_12.setObjectName("label_12")
        self.blocksize = QtGui.QLineEdit(self.frame_18)
        self.blocksize.setGeometry(QtCore.QRect(6, 20, 141, 22))
        self.blocksize.setObjectName("blocksize")
        self.frame_6 = QtGui.QFrame(self.frame_7)
        self.frame_6.setGeometry(QtCore.QRect(6, 332, 313, 29))
        self.frame_6.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label = QtGui.QLabel(self.frame_6)
        self.label.setGeometry(QtCore.QRect(2, 4, 101, 20))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.plotterselection = QtGui.QComboBox(self.frame_6)
        self.plotterselection.setGeometry(QtCore.QRect(142, 0, 171, 26))
        self.plotterselection.setEditable(False)
        self.plotterselection.setObjectName("plotterselection")
        self.plotterselection.addItem(QtCore.QString())
        self.plotterselection.addItem(QtCore.QString())
        self.plotterselection.addItem(QtCore.QString())
        self.plotterselection.addItem(QtCore.QString())
        self.plotterselection.addItem(QtCore.QString())
        self.frame_13 = QtGui.QFrame(self.frame_7)
        self.frame_13.setGeometry(QtCore.QRect(8, 390, 313, 31))
        self.frame_13.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_13.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.label_5 = QtGui.QLabel(self.frame_13)
        self.label_5.setGeometry(QtCore.QRect(12, 4, 81, 20))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.windowselection = QtGui.QComboBox(self.frame_13)
        self.windowselection.setGeometry(QtCore.QRect(140, 0, 171, 26))
        self.windowselection.setEditable(False)
        self.windowselection.setObjectName("windowselection")
        self.windowselection.addItem(QtCore.QString())
        self.windowselection.addItem(QtCore.QString())
        self.frame_11 = QtGui.QFrame(self.frame_7)
        self.frame_11.setGeometry(QtCore.QRect(2, 360, 319, 31))
        self.frame_11.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_11.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.label_4 = QtGui.QLabel(self.frame_11)
        self.label_4.setGeometry(QtCore.QRect(8, 4, 41, 20))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.panelselection = QtGui.QComboBox(self.frame_11)
        self.panelselection.setGeometry(QtCore.QRect(146, 0, 171, 26))
        self.panelselection.setEditable(False)
        self.panelselection.setObjectName("panelselection")
        self.panelselection.addItem(QtCore.QString())
        self.panelselection.addItem(QtCore.QString())
        self.panelselection.addItem(QtCore.QString())
        self.groupBox = QtGui.QGroupBox(self.widget)
        self.groupBox.setGeometry(QtCore.QRect(0, -18, 315, 51))
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName("groupBox")
        self.mouse_zoom = QtGui.QRadioButton(self.groupBox)
        self.mouse_zoom.setGeometry(QtCore.QRect(4, 22, 101, 21))
        self.mouse_zoom.setChecked(True)
        self.mouse_zoom.setObjectName("mouse_zoom")
        self.mouse_value = QtGui.QRadioButton(self.groupBox)
        self.mouse_value.setGeometry(QtCore.QRect(62, 22, 101, 21))
        self.mouse_value.setObjectName("mouse_value")
        self.mouse_select = QtGui.QRadioButton(self.groupBox)
        self.mouse_select.setGeometry(QtCore.QRect(126, 22, 101, 21))
        self.mouse_select.setObjectName("mouse_select")
        self.MouseSelectMode = QtGui.QComboBox(self.groupBox)
        self.MouseSelectMode.setGeometry(QtCore.QRect(200, 18, 111, 26))
        self.MouseSelectMode.setMaxVisibleItems(10)
        self.MouseSelectMode.setMaxCount(2147483646)
        self.MouseSelectMode.setObjectName("MouseSelectMode")
        self.MouseSelectMode.addItem(QtCore.QString())
        self.MouseSelectMode.addItem(QtCore.QString())
        self.MouseSelectMode.addItem(QtCore.QString())
        self.replot = QtGui.QPushButton(self.widget)
        self.replot.setGeometry(QtCore.QRect(0, 578, 75, 24))
        self.replot.setObjectName("replot")
        self.quit = QtGui.QPushButton(self.widget)
        self.quit.setGeometry(QtCore.QRect(246, 578, 75, 24))
        self.quit.setObjectName("quit")
        self.frame_2 = QtGui.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(335, 502, 781, 117))
        self.frame_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.consoleoutput = QtGui.QTextEdit(self.frame_2)
        self.consoleoutput.setGeometry(QtCore.QRect(6, 2, 769, 85))
        self.consoleoutput.setReadOnly(True)
        self.consoleoutput.setAcceptRichText(False)
        self.consoleoutput.setObjectName("consoleoutput")
        self.consoleinput = QtGui.QLineEdit(self.frame_2)
        self.consoleinput.setGeometry(QtCore.QRect(24, 92, 575, 22))
        self.consoleinput.setObjectName("consoleinput")
        self.label_21 = QtGui.QLabel(self.frame_2)
        self.label_21.setGeometry(QtCore.QRect(2, 92, 23, 17))
        self.label_21.setObjectName("label_21")
        self.DBGContinueButton = QtGui.QPushButton(self.frame_2)
        self.DBGContinueButton.setGeometry(QtCore.QRect(724, 90, 51, 23))
        self.DBGContinueButton.setObjectName("DBGContinueButton")
        self.DBGStopButton = QtGui.QPushButton(self.frame_2)
        self.DBGStopButton.setGeometry(QtCore.QRect(680, 90, 51, 23))
        self.DBGStopButton.setObjectName("DBGStopButton")
        self.DBGStartButton = QtGui.QPushButton(self.frame_2)
        self.DBGStartButton.setGeometry(QtCore.QRect(634, 90, 51, 23))
        self.DBGStartButton.setObjectName("DBGStartButton")
        self.label_22 = QtGui.QLabel(self.frame_2)
        self.label_22.setGeometry(QtCore.QRect(606, 96, 31, 17))
        self.label_22.setObjectName("label_22")
        self.CursorValueLabel = QtGui.QLabel(self.frame_2)
        self.CursorValueLabel.setGeometry(QtCore.QRect(644, 14, 127, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CursorValueLabel.setFont(font)
        self.CursorValueLabel.setWordWrap(True)
        self.CursorValueLabel.setObjectName("CursorValueLabel")
        self.frame_25 = QtGui.QFrame(self.frame_2)
        self.frame_25.setGeometry(QtCore.QRect(630, 8, 139, 47))
        self.frame_25.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_25.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1126, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.loadfile = QtGui.QAction(MainWindow)
        self.loadfile.setObjectName("loadfile")
        self.actionDelete = QtGui.QAction(MainWindow)
        self.actionDelete.setObjectName("actionDelete")
        self.actionSplit_Panels = QtGui.QAction(MainWindow)
        self.actionSplit_Panels.setObjectName("actionSplit_Panels")
        self.actionSelect_All = QtGui.QAction(MainWindow)
        self.actionSelect_All.setObjectName("actionSelect_All")
        self.actionDeselect_All = QtGui.QAction(MainWindow)
        self.actionDeselect_All.setObjectName("actionDeselect_All")
        self.actionShift_Left = QtGui.QAction(MainWindow)
        self.actionShift_Left.setObjectName("actionShift_Left")
        self.actionShift_Right = QtGui.QAction(MainWindow)
        self.actionShift_Right.setObjectName("actionShift_Right")
        self.actionZoom_in = QtGui.QAction(MainWindow)
        self.actionZoom_in.setObjectName("actionZoom_in")
        self.actionZoom_out = QtGui.QAction(MainWindow)
        self.actionZoom_out.setObjectName("actionZoom_out")
        self.menuFile.addAction(self.loadfile)
        self.menuEdit.addAction(self.actionDeselect_All)
        self.menuEdit.addAction(self.actionSelect_All)
        self.menuEdit.addAction(self.actionDelete)
        self.menuEdit.addAction(self.actionSplit_Panels)
        self.menuView.addAction(self.actionZoom_in)
        self.menuView.addAction(self.actionZoom_out)
        self.menuView.addAction(self.actionShift_Right)
        self.menuView.addAction(self.actionShift_Left)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(MainWindow)
        self.tabwindow.setCurrentIndex(0)
        self.netlevel.setCurrentIndex(1)
        self.comboBox.setCurrentIndex(3)
        self.MouseSelectMode.setCurrentIndex(2)
        QtCore.QObject.connect(self.npanels, QtCore.SIGNAL("returnPressed()"), self.HMainPlotter.hfsetNPanels)
        QtCore.QObject.connect(self.quit, QtCore.SIGNAL("clicked()"), self.HMainPlotter.quit)
        QtCore.QObject.connect(self.replot, QtCore.SIGNAL("clicked()"), self.HMainPlotter.hfReplotNetwork)
        QtCore.QObject.connect(self.npanelsx, QtCore.SIGNAL("returnPressed()"), self.HMainPlotter.hfsetNPanelsx)
        QtCore.QObject.connect(self.npanelsy, QtCore.SIGNAL("returnPressed()"), self.HMainPlotter.hfsetNPanelsy)
        QtCore.QObject.connect(self.xmin, QtCore.SIGNAL("returnPressed()"), self.HMainPlotter.hfsetXMin)
        QtCore.QObject.connect(self.xmax, QtCore.SIGNAL("returnPressed()"), self.HMainPlotter.hfsetXMax)
        QtCore.QObject.connect(self.ymin, QtCore.SIGNAL("returnPressed()"), self.HMainPlotter.hfsetYMin)
        QtCore.QObject.connect(self.ymax, QtCore.SIGNAL("returnPressed()"), self.HMainPlotter.hfsetYMax)
        QtCore.QObject.connect(self.xdatatype, QtCore.SIGNAL("textChanged(QString)"), self.HMainPlotter.xdatatype)
        QtCore.QObject.connect(self.netlevel, QtCore.SIGNAL("textChanged(QString)"), self.HMainPlotter.netlevel)
        QtCore.QObject.connect(self.ydatatype, QtCore.SIGNAL("textChanged(QString)"), self.HMainPlotter.ydatatype)
        QtCore.QObject.connect(self.xauto, QtCore.SIGNAL("toggled(bool)"), self.HMainPlotter.hfsetXAuto)
        QtCore.QObject.connect(self.yauto, QtCore.SIGNAL("toggled(bool)"), self.HMainPlotter.hfsetYAuto)
        QtCore.QObject.connect(self.xzoomdial, QtCore.SIGNAL("valueChanged(int)"), self.HMainPlotter.hfsetXScale)
        QtCore.QObject.connect(self.yzoomdial, QtCore.SIGNAL("valueChanged(int)"), self.HMainPlotter.hfsetYScale)
        QtCore.QObject.connect(self.yshiftslider, QtCore.SIGNAL("valueChanged(int)"), self.HMainPlotter.hfsetYShift)
        QtCore.QObject.connect(self.xshiftslider, QtCore.SIGNAL("valueChanged(int)"), self.HMainPlotter.hfsetXShift)
        QtCore.QObject.connect(self.yreset, QtCore.SIGNAL("clicked()"), self.HMainPlotter.hfYReset)
        QtCore.QObject.connect(self.xreset, QtCore.SIGNAL("clicked()"), self.HMainPlotter.hfXReset)
        QtCore.QObject.connect(self.networkdisplayon, QtCore.SIGNAL("clicked(bool)"), self.HMainPlotter.hfsetNetworkOn)
        QtCore.QObject.connect(self.xaxisunit, QtCore.SIGNAL("textChanged(QString)"), self.HMainPlotter.xaxisunitscale)
        QtCore.QObject.connect(self.yaxisunit, QtCore.SIGNAL("textChanged(QString)"), self.HMainPlotter.yaxisunitscale)
        QtCore.QObject.connect(self.consoleinput, QtCore.SIGNAL("returnPressed()"), self.HMainPlotter.hfConsoleInput)
        QtCore.QObject.connect(self.DBGContinueButton, QtCore.SIGNAL("clicked()"), self.HMainPlotter.hfDBGContinueButtonPressed)
        QtCore.QObject.connect(self.DBGStopButton, QtCore.SIGNAL("clicked()"), self.HMainPlotter.hfDBGStopButtonPressed)
        QtCore.QObject.connect(self.DBGStartButton, QtCore.SIGNAL("clicked()"), self.HMainPlotter.hfDBGStartButtonPressed)
        QtCore.QObject.connect(self.logy, QtCore.SIGNAL("clicked(bool)"), self.HMainPlotter.hflogYaxis)
        QtCore.QObject.connect(self.logx, QtCore.SIGNAL("clicked(bool)"), self.HMainPlotter.hflogXaxis)
        QtCore.QObject.connect(self.pushButton_2, QtCore.SIGNAL("clicked()"), self.HMainPlotter.hfReplotNetwork)
        QtCore.QObject.connect(self.firstantenna, QtCore.SIGNAL("editingFinished()"), self.HMainPlotter.hffirstantenna)
        QtCore.QObject.connect(self.lastantenna, QtCore.SIGNAL("editingFinished()"), self.HMainPlotter.hflastantenna)
        QtCore.QObject.connect(self.antennaselection, QtCore.SIGNAL("editingFinished()"), self.HMainPlotter.hfantennaselection)
        QtCore.QObject.connect(self.add_fx, QtCore.SIGNAL("currentIndexChanged(QString)"), self.HMainPlotter.hfadd_fx)
        QtCore.QObject.connect(self.add_fy, QtCore.SIGNAL("currentIndexChanged(QString)"), self.HMainPlotter.hfadd_fy)
        QtCore.QObject.connect(self.remove_fx, QtCore.SIGNAL("clicked()"), self.HMainPlotter.hfremove_fx)
        QtCore.QObject.connect(self.remove_fy, QtCore.SIGNAL("clicked()"), self.HMainPlotter.hfremove_fy)
        QtCore.QObject.connect(self.view_fxchain_2, QtCore.SIGNAL("clicked()"), self.HMainPlotter.hfview_fy)
        QtCore.QObject.connect(self.view_fxchain, QtCore.SIGNAL("clicked()"), self.HMainPlotter.hfview_fx)
        QtCore.QObject.connect(self.mouse_zoom, QtCore.SIGNAL("clicked()"), self.HMainPlotter.hfmouse_zoom)
        QtCore.QObject.connect(self.mouse_value, QtCore.SIGNAL("clicked()"), self.HMainPlotter.hfmouse_value)
        QtCore.QObject.connect(self.mouse_select, QtCore.SIGNAL("clicked()"), self.HMainPlotter.hfmouse_select)
        QtCore.QObject.connect(self.MouseSelectMode, QtCore.SIGNAL("currentIndexChanged(QString)"), self.HMainPlotter.hfmouse_selectwhat)
        QtCore.QObject.connect(self.networkzoom, QtCore.SIGNAL("sliderMoved(int)"), self.networkdisplay.zoom)
        QtCore.QObject.connect(self.networkaspectslider, QtCore.SIGNAL("sliderMoved(int)"), self.networkdisplay.aspect)
        QtCore.QObject.connect(self.actionShift_Left, QtCore.SIGNAL("activated()"), self.HMainPlotter.hfshift_left)
        QtCore.QObject.connect(self.actionShift_Right, QtCore.SIGNAL("activated()"), self.HMainPlotter.hfshift_right)
        QtCore.QObject.connect(self.actionZoom_in, QtCore.SIGNAL("triggered()"), self.HMainPlotter.hfzoom_in)
        QtCore.QObject.connect(self.actionZoom_out, QtCore.SIGNAL("triggered()"), self.HMainPlotter.hfzoom_out)
        QtCore.QObject.connect(self.comboBox, QtCore.SIGNAL("currentIndexChanged(QString)"), self.HMainPlotter.hfsetBlocksize)
        QtCore.QObject.connect(self.blocknumber, QtCore.SIGNAL("valueChanged(int)"), self.blocknumberslider.setValue)
        QtCore.QObject.connect(self.blocknumber, QtCore.SIGNAL("valueChanged(int)"), self.HMainPlotter.hfsetBlock)
        QtCore.QObject.connect(self.blocknumberslider, QtCore.SIGNAL("valueChanged(int)"), self.blocknumber.setValue)
        QtCore.QObject.connect(self.blocknumber, QtCore.SIGNAL("valueChanged(QString)"), self.lineEdit.setText)
        QtCore.QObject.connect(self.lineEdit, QtCore.SIGNAL("returnPressed()"), self.HMainPlotter.hfsetBlockPressed)
        QtCore.QObject.connect(self.blocksize, QtCore.SIGNAL("returnPressed()"), self.HMainPlotter.hfsetBlocksizePressed)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        MainWindow.setToolTip(QtGui.QApplication.translate("MainWindow", "Aspect", None, QtGui.QApplication.UnicodeUTF8))
        MainWindow.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Python Console Input", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.tabwindow.setTabText(self.tabwindow.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Plot Window", None, QtGui.QApplication.UnicodeUTF8))
        self.networkzoom.setToolTip(QtGui.QApplication.translate("MainWindow", "Zoom", None, QtGui.QApplication.UnicodeUTF8))
        self.networkaspectslider.setToolTip(QtGui.QApplication.translate("MainWindow", "Aspect", None, QtGui.QApplication.UnicodeUTF8))
        self.tabwindow.setTabText(self.tabwindow.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Network Display", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "# Panels:", None, QtGui.QApplication.UnicodeUTF8))
        self.panelauto.setText(QtGui.QApplication.translate("MainWindow", "Auto", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", " col x row:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Antennas:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "x-Axis:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "y-Axis:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "Unit:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "Unit:", None, QtGui.QApplication.UnicodeUTF8))
        self.logx.setToolTip(QtGui.QApplication.translate("MainWindow", "logarithmic x-axis", None, QtGui.QApplication.UnicodeUTF8))
        self.logx.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Selects whether x-axis scale is logarithmic", None, QtGui.QApplication.UnicodeUTF8))
        self.logx.setText(QtGui.QApplication.translate("MainWindow", "log", None, QtGui.QApplication.UnicodeUTF8))
        self.logy.setToolTip(QtGui.QApplication.translate("MainWindow", "logarithmic y-axis", None, QtGui.QApplication.UnicodeUTF8))
        self.logy.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Selects whether y-axis scale is logarithmic", None, QtGui.QApplication.UnicodeUTF8))
        self.logy.setText(QtGui.QApplication.translate("MainWindow", "log", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "y-Axis", None, QtGui.QApplication.UnicodeUTF8))
        self.yauto.setText(QtGui.QApplication.translate("MainWindow", "Auto", None, QtGui.QApplication.UnicodeUTF8))
        self.yzoomdial.setToolTip(QtGui.QApplication.translate("MainWindow", "y-Axis Zoom", None, QtGui.QApplication.UnicodeUTF8))
        self.yshiftslider.setToolTip(QtGui.QApplication.translate("MainWindow", "y-Axis sliding Window", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.yreset.setText(QtGui.QApplication.translate("MainWindow", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "x-Axis", None, QtGui.QApplication.UnicodeUTF8))
        self.xauto.setText(QtGui.QApplication.translate("MainWindow", "Auto", None, QtGui.QApplication.UnicodeUTF8))
        self.xzoomdial.setToolTip(QtGui.QApplication.translate("MainWindow", "x-Axis Zoom", None, QtGui.QApplication.UnicodeUTF8))
        self.xshiftslider.setToolTip(QtGui.QApplication.translate("MainWindow", "x-Axis sliding window ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.xreset.setText(QtGui.QApplication.translate("MainWindow", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Level:", None, QtGui.QApplication.UnicodeUTF8))
        self.netlevel.setItemText(0, QtGui.QApplication.translate("MainWindow", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.netlevel.setItemText(1, QtGui.QApplication.translate("MainWindow", "99", None, QtGui.QApplication.UnicodeUTF8))
        self.netlevel.setItemText(2, QtGui.QApplication.translate("MainWindow", "100", None, QtGui.QApplication.UnicodeUTF8))
        self.netlevel.setItemText(3, QtGui.QApplication.translate("MainWindow", "999", None, QtGui.QApplication.UnicodeUTF8))
        self.netlevel.setItemText(4, QtGui.QApplication.translate("MainWindow", "9999", None, QtGui.QApplication.UnicodeUTF8))
        self.networkdisplayon.setToolTip(QtGui.QApplication.translate("MainWindow", "Real-time updating of Network Display", None, QtGui.QApplication.UnicodeUTF8))
        self.networkdisplayon.setText(QtGui.QApplication.translate("MainWindow", "Network Display", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("MainWindow", "Redo", None, QtGui.QApplication.UnicodeUTF8))
        self.remove_fy.setText(QtGui.QApplication.translate("MainWindow", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("MainWindow", "f(y):", None, QtGui.QApplication.UnicodeUTF8))
        self.view_fxchain_2.setText(QtGui.QApplication.translate("MainWindow", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.remove_fx.setText(QtGui.QApplication.translate("MainWindow", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("MainWindow", "f(x):", None, QtGui.QApplication.UnicodeUTF8))
        self.view_fxchain.setText(QtGui.QApplication.translate("MainWindow", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.blocknumber.setToolTip(QtGui.QApplication.translate("MainWindow", "Block Number", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Block Number:", None, QtGui.QApplication.UnicodeUTF8))
        self.blocknumberslider.setToolTip(QtGui.QApplication.translate("MainWindow", "Block Size", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit.setToolTip(QtGui.QApplication.translate("MainWindow", "Enter Block number and press return", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setToolTip(QtGui.QApplication.translate("MainWindow", "Select a Blocksize from (editable) list", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "128", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "256", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "512", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(3, QtGui.QApplication.translate("MainWindow", "1024", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(4, QtGui.QApplication.translate("MainWindow", "2048", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(5, QtGui.QApplication.translate("MainWindow", "4096", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(6, QtGui.QApplication.translate("MainWindow", "8192", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(7, QtGui.QApplication.translate("MainWindow", "16384", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(8, QtGui.QApplication.translate("MainWindow", "32768", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(9, QtGui.QApplication.translate("MainWindow", "65536", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(10, QtGui.QApplication.translate("MainWindow", "131072", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(11, QtGui.QApplication.translate("MainWindow", "262144", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(12, QtGui.QApplication.translate("MainWindow", "524288", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(13, QtGui.QApplication.translate("MainWindow", "1048576", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Block  Size:", None, QtGui.QApplication.UnicodeUTF8))
        self.blocksize.setToolTip(QtGui.QApplication.translate("MainWindow", "Enter Blocksize and press return", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Data Plotter:", None, QtGui.QApplication.UnicodeUTF8))
        self.plotterselection.setItemText(0, QtGui.QApplication.translate("MainWindow", "Selected Window", None, QtGui.QApplication.UnicodeUTF8))
        self.plotterselection.setItemText(1, QtGui.QApplication.translate("MainWindow", "Selected Panel", None, QtGui.QApplication.UnicodeUTF8))
        self.plotterselection.setItemText(2, QtGui.QApplication.translate("MainWindow", "All Lines", None, QtGui.QApplication.UnicodeUTF8))
        self.plotterselection.setItemText(3, QtGui.QApplication.translate("MainWindow", "Line 1", None, QtGui.QApplication.UnicodeUTF8))
        self.plotterselection.setItemText(4, QtGui.QApplication.translate("MainWindow", "Line 2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Window:", None, QtGui.QApplication.UnicodeUTF8))
        self.windowselection.setItemText(0, QtGui.QApplication.translate("MainWindow", "All Windows", None, QtGui.QApplication.UnicodeUTF8))
        self.windowselection.setItemText(1, QtGui.QApplication.translate("MainWindow", "Window 1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Panel:", None, QtGui.QApplication.UnicodeUTF8))
        self.panelselection.setItemText(0, QtGui.QApplication.translate("MainWindow", "Selected Windows", None, QtGui.QApplication.UnicodeUTF8))
        self.panelselection.setItemText(1, QtGui.QApplication.translate("MainWindow", "All Panels", None, QtGui.QApplication.UnicodeUTF8))
        self.panelselection.setItemText(2, QtGui.QApplication.translate("MainWindow", "Panel 1", None, QtGui.QApplication.UnicodeUTF8))
        self.mouse_zoom.setToolTip(QtGui.QApplication.translate("MainWindow", "Change the cursor to zoom into the data", None, QtGui.QApplication.UnicodeUTF8))
        self.mouse_zoom.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Change the cursor to zoom into the data", None, QtGui.QApplication.UnicodeUTF8))
        self.mouse_zoom.setText(QtGui.QApplication.translate("MainWindow", "Zoom", None, QtGui.QApplication.UnicodeUTF8))
        self.mouse_value.setToolTip(QtGui.QApplication.translate("MainWindow", "Give the (data) values at cursor position", None, QtGui.QApplication.UnicodeUTF8))
        self.mouse_value.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Give the (data) values at cursor position", None, QtGui.QApplication.UnicodeUTF8))
        self.mouse_value.setText(QtGui.QApplication.translate("MainWindow", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.mouse_select.setText(QtGui.QApplication.translate("MainWindow", "Select", None, QtGui.QApplication.UnicodeUTF8))
        self.MouseSelectMode.setItemText(0, QtGui.QApplication.translate("MainWindow", "Values", None, QtGui.QApplication.UnicodeUTF8))
        self.MouseSelectMode.setItemText(1, QtGui.QApplication.translate("MainWindow", "Data Sets", None, QtGui.QApplication.UnicodeUTF8))
        self.MouseSelectMode.setItemText(2, QtGui.QApplication.translate("MainWindow", "Plot Panels", None, QtGui.QApplication.UnicodeUTF8))
        self.replot.setText(QtGui.QApplication.translate("MainWindow", "Replot", None, QtGui.QApplication.UnicodeUTF8))
        self.quit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.consoleoutput.setToolTip(QtGui.QApplication.translate("MainWindow", "Python Console Output", None, QtGui.QApplication.UnicodeUTF8))
        self.consoleoutput.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Python Console Output", None, QtGui.QApplication.UnicodeUTF8))
        self.consoleinput.setToolTip(QtGui.QApplication.translate("MainWindow", "Python Console Input", None, QtGui.QApplication.UnicodeUTF8))
        self.consoleinput.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Python Console Input: Evaluate Python expressions. Use ! to execute a statement and, e.g., assign a variable. Note, however, that you need to declare a variable as global if you want to access it from the propmpt: \"!global x=1\" would work.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("MainWindow", ">>", None, QtGui.QApplication.UnicodeUTF8))
        self.DBGContinueButton.setText(QtGui.QApplication.translate("MainWindow", "Cont", None, QtGui.QApplication.UnicodeUTF8))
        self.DBGStopButton.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.DBGStartButton.setText(QtGui.QApplication.translate("MainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("MainWindow", "DBG:", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdit.setTitle(QtGui.QApplication.translate("MainWindow", "&Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuView.setTitle(QtGui.QApplication.translate("MainWindow", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.loadfile.setText(QtGui.QApplication.translate("MainWindow", "&Load ...", None, QtGui.QApplication.UnicodeUTF8))
        self.loadfile.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDelete.setText(QtGui.QApplication.translate("MainWindow", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDelete.setShortcut(QtGui.QApplication.translate("MainWindow", "Backspace", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSplit_Panels.setText(QtGui.QApplication.translate("MainWindow", "Split Panels", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSplit_Panels.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSelect_All.setText(QtGui.QApplication.translate("MainWindow", "Select All", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSelect_All.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+A", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDeselect_All.setText(QtGui.QApplication.translate("MainWindow", "Deselect All", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDeselect_All.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+D", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShift_Left.setText(QtGui.QApplication.translate("MainWindow", "Shift Left", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShift_Left.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Left", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShift_Right.setText(QtGui.QApplication.translate("MainWindow", "Shift Right", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShift_Right.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Right", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoom_in.setText(QtGui.QApplication.translate("MainWindow", "Zoom in", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoom_in.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl++", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoom_out.setText(QtGui.QApplication.translate("MainWindow", "Zoom out", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoom_out.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+-", None, QtGui.QApplication.UnicodeUTF8))

