#undef HF_PP_FUNCNAME
#undef HF_PP_FUNCTYPE
#undef HF_PP_NVECS

#undef HF_PP_NPAR
#undef HF_PP_PAR0
#undef HF_PP_PAR1
#undef HF_PP_PAR2

#undef HF_PP_VEC_WRAPPER_CODE_STL
#undef HF_PP_VEC_WRAPPER_CODE_CASA
