#ifdef HFPP_FUNCTYPE_T
#undef HFPP_FUNCTYPE_T
#endif

#undef HFPP_FUNCNAME
#undef HFPP_ALT_FUNCNAME
#undef HFPP_FUNCTYPE
#undef HFPP_FUNCBRIEF
#undef HFPP_VARIANT

#undef HFPP_NVECS
#undef HFPP_NPAR

#undef HFPP_PAR0
#undef HFPP_PAR1
#undef HFPP_PAR2
#undef HFPP_PAR3
#undef HFPP_PAR4
#undef HFPP_PAR5
#undef HFPP_PAR6
#undef HFPP_PAR7
#undef HFPP_PAR8
#undef HFPP_PAR9
#undef HFPP_PAR10

#undef HFPP_VEC_WRAPPER_CODE_STL
#undef HFPP_VEC_WRAPPER_CODE_CASA

#undef HFPP_GUI_RETURN_POLICY
#undef HFPP_GUI_LIBRARY
#undef HFPP_NO_GUI
