/*-------------------------------------------------------------------------*
 | $Id::                                                                 $ |
 *-------------------------------------------------------------------------*
 ***************************************************************************
 *   Copyright (C) 2010                                                    *
 *   Frank Schröder, Nunzia Palmieri                                       *
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   You should have received a copy of the GNU General Public License     *
 *   along with this program; if not, write to the                         *
 *   Free Software Foundation, Inc.,                                       *
 *   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             *
 ***************************************************************************/
 
#include<cstdlib>
#include<iostream>
#include<fstream>
#include<string>
#include<sstream>
#include<time.h>

#include<TFile.h>
#include<TTree.h>
#include<TMath.h>
#include<TCut.h>

/*!
  \file genREASinputList.cc

  \ingroup CR_Applications

  \brief Creates ASCII list from results of call_pipeline, for input to REAS

  \author Frank Schr&ouml;der, Nunzia Palmieri

  \date 2010/Apr/06

  <h3>Usage</h3>

  \verbatim
  ./genREASinputList results.root options.cfg "optional selection string"
  \endverbatim

  <h3>Prerequisites</h3>

  options.cfg

  Example:
  \verbatim
  not yet defined
  \endverbatim

*/

using namespace std;
using namespace TMath;

int main(int argc, char* argv[])
{
  try {
    if(argc!=4&&argc!=3) {
      cout << "\n Application to generate an ASCII list for REAS simulations, based on the ROOT file generated by call_pipeline.\n"
           << " Syntax: ./genREASinputList results.root options.cfg [\"optional selection string\"] "
           << endl;
      cout<<"Wrong number of arguments!"<<endl;
      return 1;
    } else {
      cout << "\nStarting genREASinputList.\n" << endl;
    }
    
    // TODO:
    // fill content here, analogue to genEventlist
  } catch (...) {
    cerr << "\ngenREASinputList: exception occurred!" << endl;
  } 
}
